package pojo.annotations.custom;

// Generated 01/08/2015 16:28:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vingresos generated by hbm2java
 */
@Entity
@Table(name = "vingresos", schema = "public")
public class Vingresos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 823656098572332568L;
	private String numidentificacion;
	private String formapago;
	private String nrodocumento;
	private String entidad;
	private Float valpago;
	private Integer idusuario;
	private Date fecha;
	private Integer idestado;
	private Integer idfpago;

	public Vingresos() {
	}

	public Vingresos(String numidentificacion, String formapago,
			String nrodocumento, String entidad, Float valpago,
			Integer idusuario, Date fecha, Integer idestado, Integer idfpago) {
		this.numidentificacion = numidentificacion;
		this.formapago = formapago;
		this.nrodocumento = nrodocumento;
		this.entidad = entidad;
		this.valpago = valpago;
		this.idusuario = idusuario;
		this.fecha = fecha;
		this.idestado = idestado;
		this.idfpago = idfpago;
	}
	
	@Id
	@Column(name = "numidentificacion", length = 45)
	public String getNumidentificacion() {
		return this.numidentificacion;
	}

	public void setNumidentificacion(String numidentificacion) {
		this.numidentificacion = numidentificacion;
	}

	@Column(name = "formapago", length = 20)
	public String getFormapago() {
		return this.formapago;
	}

	public void setFormapago(String formapago) {
		this.formapago = formapago;
	}

	@Column(name = "nrodocumento", length = 30)
	public String getNrodocumento() {
		return this.nrodocumento;
	}

	public void setNrodocumento(String nrodocumento) {
		this.nrodocumento = nrodocumento;
	}

	@Column(name = "entidad", length = 30)
	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	@Column(name = "valpago", precision = 8, scale = 8)
	public Float getValpago() {
		return this.valpago;
	}

	public void setValpago(Float valpago) {
		this.valpago = valpago;
	}

	@Column(name = "idusuario")
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idestado")
	public Integer getIdestado() {
		return this.idestado;
	}

	public void setIdestado(Integer idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idfpago")
	public Integer getIdfpago() {
		return this.idfpago;
	}

	public void setIdfpago(Integer idfpago) {
		this.idfpago = idfpago;
	}

}
