package pojo.annotations.custom;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vmenu generated by hbm2java
 */
@Entity
@Table(name = "vmenu", schema = "public")
public class Vmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4094298193717640562L;
	private Integer idmenu;
	private String nombre;
	private String descripcion;
	private String abreviado;
	private Integer idmenupadre;
	private Integer nivel;
	private String iconourl;
	private String paginaurl;
	private Integer orden;
	private int idestado;
	private int idempresa;
	private int idtipomenu;

	public Vmenu() {
	}

	public Vmenu(Integer idmenu, String nombre, String descripcion,
			String abreviado, Integer idmenupadre, Integer nivel,
			String iconourl, String paginaurl, Integer orden, int idestado,
			int idempresa, int idtipomenu) {
		this.idmenu = idmenu;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.abreviado = abreviado;
		this.idmenupadre = idmenupadre;
		this.nivel = nivel;
		this.iconourl = iconourl;
		this.paginaurl = paginaurl;
		this.orden = orden;
		this.idestado = idestado;
		this.idempresa = idempresa;
		this.idtipomenu = idtipomenu;
	}

	@Id
	@Column(name = "idmenu")
	public Integer getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(Integer idmenu) {
		this.idmenu = idmenu;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idmenupadre")
	public Integer getIdmenupadre() {
		return this.idmenupadre;
	}

	public void setIdmenupadre(Integer idmenupadre) {
		this.idmenupadre = idmenupadre;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "iconourl", length = 100)
	public String getIconourl() {
		return this.iconourl;
	}

	public void setIconourl(String iconourl) {
		this.iconourl = iconourl;
	}

	@Column(name = "paginaurl", length = 200)
	public String getPaginaurl() {
		return this.paginaurl;
	}

	public void setPaginaurl(String paginaurl) {
		this.paginaurl = paginaurl;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "idestado")
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idempresa")
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "idtipomenu")
	public int getIdtipomenu() {
		return this.idtipomenu;
	}

	public void setIdtipomenu(int idtipomenu) {
		this.idtipomenu = idtipomenu;
	}

}
