package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", schema = "public")
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -65042348959822823L;
	private int idarea;
	private Estado estado;
	private Usuario usuario;
	private Empresa empresa;
	private String nombre;
	private Date fecha;
	//private Set<?> modcronogramas = new HashSet<Object>(0);

	public Area() {
	}

	public Area(int idarea, Estado estado, Usuario usuario, Empresa empresa,
			String nombre, Date fecha) {
		this.idarea = idarea;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre = nombre;
		this.fecha = fecha;
	}

	/*public Area(int idarea, Estado estado, Usuario usuario, Empresa empresa,
			String nombre, Date fecha, Set<?> modcronogramas) {
		this.idarea = idarea;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre = nombre;
		this.fecha = fecha;
		this.modcronogramas = modcronogramas;
	}*/

	@Id
	@Column(name = "idarea", unique = true, nullable = false)
	public int getIdarea() {
		return this.idarea;
	}

	public void setIdarea(int idarea) {
		this.idarea = idarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "area", targetEntity=Modcronograma.class)
	public Set<?> getModcronogramas() {
		return this.modcronogramas;
	}

	public void setModcronogramas(Set<?> modcronogramas) {
		this.modcronogramas = modcronogramas;
	}*/

}
