package pojo.annotations;

// Generated 13/03/2014 06:57:41 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cabimpfacturas generated by hbm2java
 */
@Entity
@Table(name = "cabimpfacturas", schema = "public")
public class Cabimpfacturas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8513004764693223317L;
	private int idcabfactura;
	private String resolucion;
	private String autorizacion;
	private String idfactura;
	private String dircinecable;
	private String dircliente;
	private String idcliente;
	private String nomscliente;
	private String telcliente;
	private int idempresa;
	private Integer idestado;
	private Float totalfactura;
	private Float subtotal;
	private Float valimpiva;
	private Float valimpice;
	private Float valdescre;
	private Integer idcuenta;

	public Cabimpfacturas() {
	}

	public Cabimpfacturas(int idcabfactura, int idempresa) {
		this.idcabfactura = idcabfactura;
		this.idempresa = idempresa;
	}

	public Cabimpfacturas(int idcabfactura, String resolucion,
			String autorizacion, String idfactura, String dircinecable,
			String dircliente, String idcliente, String nomscliente,
			String telcliente, int idempresa, Integer idestado,
			Float totalfactura, Float subtotal, Float valimpiva,
			Float valimpice, Float valdescre, Integer idcuenta) {
		this.idcabfactura = idcabfactura;
		this.resolucion = resolucion;
		this.autorizacion = autorizacion;
		this.idfactura = idfactura;
		this.dircinecable = dircinecable;
		this.dircliente = dircliente;
		this.idcliente = idcliente;
		this.nomscliente = nomscliente;
		this.telcliente = telcliente;
		this.idempresa = idempresa;
		this.idestado = idestado;
		this.totalfactura = totalfactura;
		this.subtotal = subtotal;
		this.valimpiva = valimpiva;
		this.valimpice = valimpice;
		this.valdescre = valdescre;
		this.idcuenta = idcuenta;
	}

	@Id
	@Column(name = "idcabfactura", unique = true, nullable = false)
	public int getIdcabfactura() {
		return this.idcabfactura;
	}

	public void setIdcabfactura(int idcabfactura) {
		this.idcabfactura = idcabfactura;
	}

	@Column(name = "resolucion", length = 50)
	public String getResolucion() {
		return this.resolucion;
	}

	public void setResolucion(String resolucion) {
		this.resolucion = resolucion;
	}

	@Column(name = "autorizacion")
	public String getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(String autorizacion) {
		this.autorizacion = autorizacion;
	}

	@Column(name = "idfactura", length = 50)
	public String getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(String idfactura) {
		this.idfactura = idfactura;
	}

	@Column(name = "dircinecable", length = 100)
	public String getDircinecable() {
		return this.dircinecable;
	}

	public void setDircinecable(String dircinecable) {
		this.dircinecable = dircinecable;
	}

	@Column(name = "dircliente", length = 100)
	public String getDircliente() {
		return this.dircliente;
	}

	public void setDircliente(String dircliente) {
		this.dircliente = dircliente;
	}

	@Column(name = "idcliente", length = 25)
	public String getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(String idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nomscliente", length = 100)
	public String getNomscliente() {
		return this.nomscliente;
	}

	public void setNomscliente(String nomscliente) {
		this.nomscliente = nomscliente;
	}

	@Column(name = "telcliente", length = 100)
	public String getTelcliente() {
		return this.telcliente;
	}

	public void setTelcliente(String telcliente) {
		this.telcliente = telcliente;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "idestado")
	public Integer getIdestado() {
		return this.idestado;
	}

	public void setIdestado(Integer idestado) {
		this.idestado = idestado;
	}

	@Column(name = "totalfactura", precision = 8, scale = 8)
	public Float getTotalfactura() {
		return this.totalfactura;
	}

	public void setTotalfactura(Float totalfactura) {
		this.totalfactura = totalfactura;
	}

	@Column(name = "subtotal", precision = 8, scale = 8)
	public Float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Float subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "valimpiva", precision = 8, scale = 8)
	public Float getValimpiva() {
		return this.valimpiva;
	}

	public void setValimpiva(Float valimpiva) {
		this.valimpiva = valimpiva;
	}

	@Column(name = "valimpice", precision = 8, scale = 8)
	public Float getValimpice() {
		return this.valimpice;
	}

	public void setValimpice(Float valimpice) {
		this.valimpice = valimpice;
	}

	@Column(name = "valdescre", precision = 8, scale = 8)
	public Float getValdescre() {
		return this.valdescre;
	}

	public void setValdescre(Float valdescre) {
		this.valdescre = valdescre;
	}

	@Column(name = "idcuenta")
	public Integer getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(Integer idcuenta) {
		this.idcuenta = idcuenta;
	}

}
