package pojo.annotations;

// Generated 09-feb-2014 10:19:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Callesecundaria generated by hbm2java
 */
@Entity
@Table(name = "callesecundaria", schema = "public")
public class Callesecundaria implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcallesecundaria;
	private Estado estado;
	private Usuario usuario;
	private Empresa empresa;
	private String nombre;
	private String abreviado;
	private Date fecha;
	private Sector sector;
	private Set<?> direccions = new HashSet<Object>(0);

	public Callesecundaria() {
	}

	public Callesecundaria(int idcallesecundaria, Estado estado,
			Usuario usuario, Empresa empresa, String nombre, String abreviado,
			Date fecha, Sector sector) {
	
		this.idcallesecundaria = idcallesecundaria;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.fecha = fecha;
		this.sector = sector;
	}


	public Callesecundaria(int idcallesecundaria, Estado estado,
			Usuario usuario, Empresa empresa, String nombre, String abreviado,
			Date fecha, Sector sector, Set<?> direccions) {
		
		this.idcallesecundaria = idcallesecundaria;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.fecha = fecha;
		this.sector = sector;
		this.direccions = direccions;
	}



	@Id
	@Column(name = "idcallesecundaria", unique = true, nullable = false)
	public int getIdcallesecundaria() {
		return this.idcallesecundaria;
	}

	public void setIdcallesecundaria(int idcallesecundaria) {
		this.idcallesecundaria = idcallesecundaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 8)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsector", nullable = false)
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "callesecundaria",targetEntity=Direccion.class)
	public Set<?> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<?> direccions) {
		this.direccions = direccions;
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	public Callesecundaria clonar() throws Exception {
		return (Callesecundaria)clone();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((abreviado == null) ? 0 : abreviado.hashCode());
		result = prime * result + ((empresa == null) ? 0 : empresa.getIdempresa());
		result = prime * result + ((estado == null) ? 0 : estado.getIdestado());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result + idcallesecundaria;
		result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
		result = prime * result + ((sector == null) ? 0 : sector.getIdsector());
		result = prime * result + ((usuario == null) ? 0 : usuario.getIdusuario());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Callesecundaria other = (Callesecundaria) obj;
		if (abreviado == null) {
			if (other.abreviado != null)
				return false;
		} else if (!abreviado.equals(other.abreviado))
			return false;
		if (empresa == null) {
			if (other.empresa != null)
				return false;
		} else if (empresa.getIdempresa() != other.empresa.getIdempresa())
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
		} else if (estado.getIdestado() != other.estado.getIdestado())
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (idcallesecundaria != other.idcallesecundaria)
			return false;
		if (nombre == null) {
			if (other.nombre != null)
				return false;
		} else if (!nombre.equals(other.nombre))
			return false;
		if (sector == null) {
			if (other.sector != null)
				return false;
		} else if (sector.getIdsector() != other.sector.getIdsector())
			return false;
		if (usuario == null) {
			if (other.usuario != null)
				return false;
		} else if (usuario.getIdusuario() != other.usuario.getIdusuario())
			return false;
		return true;
	}
	
	
}
