package pojo.annotations;

// Generated 04/03/2014 09:28:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cargos generated by hbm2java
 */
@Entity
@Table(name = "cargos", schema = "public")
public class Cargos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7624483894429188967L;
	private int idcargo;
	private Estado estado;
	private Factura factura;
	private Usuario usuario;
	private Empresa empresa;
	private String idfactura;
	private float valcargo;
	private short nivel;
	private Date fecha;
	private String motivo;
	private Float valpendiente;
	private Float valbase;
	private Float descuento;
	private Integer idrubropadre;
	private String producto;

	public Cargos() {
	}

	public Cargos(int idcargo, Estado estado, Factura factura, Usuario usuario,
			Empresa empresa, float valcargo, short nivel, String motivo) {
		this.idcargo = idcargo;
		this.estado = estado;
		this.factura = factura;
		this.usuario = usuario;
		this.empresa = empresa;
		this.valcargo = valcargo;
		this.nivel = nivel;
		this.motivo = motivo;
	}

	public Cargos(int idcargo, Estado estado, Factura factura, Usuario usuario,
			Empresa empresa, String idfactura, float valcargo, short nivel,
			Date fecha, String motivo, Float valpendiente, Float valbase,
			Float descuento, Integer idrubropadre, String producto) {
		this.idcargo = idcargo;
		this.estado = estado;
		this.factura = factura;
		this.usuario = usuario;
		this.empresa = empresa;
		this.idfactura = idfactura;
		this.valcargo = valcargo;
		this.nivel = nivel;
		this.fecha = fecha;
		this.motivo = motivo;
		this.valpendiente = valpendiente;
		this.valbase = valbase;
		this.descuento = descuento;
		this.idrubropadre = idrubropadre;
		this.producto = producto;
	}
	
	/**
	 * Constructor usado en select CargosDAO
	 * @param idfactura
	 * @param idgeneracion
	 * @param nivel
	 * @param motivo
	 * @param valpendiente
	 */
	public Cargos(String idfactura, int idsecuencia, short nivel, String motivo, Double valpendiente){
		this.idcargo = 0;
		this.estado = new Estado(0, null);
		Factura factura = new Factura();
		factura.setIdsecuencia(idsecuencia);
		this.factura = factura;
		this.usuario = new Usuario();
		this.empresa = new Empresa();
		this.idfactura = idfactura;
		this.valcargo = 0;
		this.nivel = nivel;
		this.fecha = null;
		this.motivo = motivo;
		this.valpendiente = valpendiente.floatValue();
		this.valbase = 0f;
		this.descuento = 0f;
		this.idrubropadre = 0;
	}

	@Id
	@Column(name = "idcargo", unique = true, nullable = false)
	public int getIdcargo() {
		return this.idcargo;
	}

	public void setIdcargo(int idcargo) {
		this.idcargo = idcargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsecuencia", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "idfactura", length = 50)
	public String getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(String idfactura) {
		this.idfactura = idfactura;
	}

	@Column(name = "valcargo", nullable = false, precision = 8, scale = 8)
	public float getValcargo() {
		return this.valcargo;
	}

	public void setValcargo(float valcargo) {
		this.valcargo = valcargo;
	}

	@Column(name = "nivel", nullable = false)
	public short getNivel() {
		return this.nivel;
	}

	public void setNivel(short nivel) {
		this.nivel = nivel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "motivo", nullable = false, length = 50)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "valpendiente", precision = 8, scale = 8)
	public Float getValpendiente() {
		return this.valpendiente;
	}

	public void setValpendiente(Float valpendiente) {
		this.valpendiente = valpendiente;
	}

	@Column(name = "valbase", precision = 8, scale = 8)
	public Float getValbase() {
		return this.valbase;
	}

	public void setValbase(Float valbase) {
		this.valbase = valbase;
	}

	@Column(name = "descuento", precision = 8, scale = 8)
	public Float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Float descuento) {
		this.descuento = descuento;
	}

	@Column(name = "idrubropadre")
	public Integer getIdrubropadre() {
		return this.idrubropadre;
	}

	public void setIdrubropadre(Integer idrubropadre) {
		this.idrubropadre = idrubropadre;
	}
	
	@Column(name = "producto", length = 150)
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

}
