package pojo.annotations;

//Generated 04/07/2015 13:17:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Cierrecajadet generated by hbm2java
*/
@Entity
@Table(name = "cierrecajadet", schema = "public")
public class Cierrecajadet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1864685776162691247L;
	private CierrecajadetId id;
	private Cierrecaja cierrecaja;
	private float total;
	private String ingresoegreso;
	private Fpago fpago;
	private Estado estado;
	private Empresa empresa;
	private Usuario usuario;
	private Date fecha;
	private String iplog;

	public Cierrecajadet() {
	}

	public Cierrecajadet(CierrecajadetId id,Cierrecaja cierrecaja,Fpago fpago,Estado estado,Empresa empresa,Usuario usuario) {
		this.id = id;
		this.cierrecaja = cierrecaja;
		this.fpago = fpago;
		this.estado = estado;
		this.empresa = empresa;
		this.usuario = usuario;
	}

	public Cierrecajadet(CierrecajadetId id, Cierrecaja cierrecaja,
			float total, String ingresoegreso, Fpago fpago,Estado estado,
			Empresa empresa,Usuario usuario, Date fecha,
			String iplog) {
		this.id = id;
		this.cierrecaja = cierrecaja;
		this.total = total;
		this.ingresoegreso = ingresoegreso;
		this.fpago = fpago;
		this.estado = estado;
		this.empresa = empresa;
		this.usuario = usuario;
		this.fecha = fecha;
		this.iplog = iplog;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idcierrecaja", column = @Column(name = "idcierrecaja", nullable = false)),
			@AttributeOverride(name = "idsecuencia", column = @Column(name = "idsecuencia", nullable = false)) })
	public CierrecajadetId getId() {
		return this.id;
	}

	public void setId(CierrecajadetId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcierrecaja", nullable = false, insertable = false, updatable = false)
	public Cierrecaja getCierrecaja() {
		return this.cierrecaja;
	}

	public void setCierrecaja(Cierrecaja cierrecaja) {
		this.cierrecaja = cierrecaja;
	}

	@Column(name = "total", precision = 8, scale = 8)
	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}
	
	@Column(name = "ingresoegreso", length = 2)
	public String getIngresoegreso() {
		return this.ingresoegreso;
	}

	public void setIngresoegreso(String ingresoegreso) {
		this.ingresoegreso = ingresoegreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfpago", nullable = false)
	public Fpago getFpago() {
		return fpago;
	}

	public void setFpago(Fpago fpago) {
		this.fpago = fpago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
