package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", schema = "public")
public class Clientes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4519133304385704972L;
	private String idcliente;
	private Tipocliente tipocliente;
	private Usuario usuario;
	private Empresa empresa;
	private String nombre1;
	private String nombre2;
	private String apellido1;
	private String apellido2;
	private String empresa_1;
	private Date fecha;
	private Date fechanacimiento;
	private String email;
	private String identificacion;
	private int estadocivil;
	private int genero;
	private int idtipoidentificacion;
	private int idtipopersona;
	private String ip;
	//private Set<?> conyuges = new HashSet<Object>(0);
	//private Set<?> ctaclientes = new HashSet<Object>(0);

	public Clientes() {
	}

	public Clientes(String idcliente, Tipocliente tipocliente, Usuario usuario,
			Empresa empresa, String nombre1, String apellido1, Date fecha) {
		this.idcliente = idcliente;
		this.tipocliente = tipocliente;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre1 = nombre1;
		this.apellido1 = apellido1;
		this.fecha = fecha;
	}

	public Clientes(String idcliente, Tipocliente tipocliente, Usuario usuario,
			Empresa empresa, String nombre1, String nombre2, String apellido1,
			String apellido2, String empresa_1, Date fecha, Date fechanacimiento, String email, int estadocivil, int genero/*,
			Set<?> conyuges, Set<?> ctaclientes*/, int idtipoidentificacion, int idtipopersona) {
		this.idcliente = idcliente;
		this.tipocliente = tipocliente;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre1 = nombre1;
		this.nombre2 = nombre2;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.empresa_1 = empresa_1;
		this.fecha = fecha;
		this.fechanacimiento = fechanacimiento;
		this.email = email;
		this.estadocivil = estadocivil;
		this.genero = genero;
		this.idtipoidentificacion = idtipoidentificacion;
		this.idtipopersona = idtipopersona;
		/*this.conyuges = conyuges;
		this.ctaclientes = ctaclientes;*/
	}

	@Id
	@Column(name = "idcliente", unique = true, nullable = false, length = 20)
	public String getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(String idcliente) {
		this.idcliente = idcliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipocliente", nullable = false)
	public Tipocliente getTipocliente() {
		return this.tipocliente;
	}

	public void setTipocliente(Tipocliente tipocliente) {
		this.tipocliente = tipocliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre1", nullable = false, length = 25)
	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	@Column(name = "nombre2", length = 25)
	public String getNombre2() {
		return this.nombre2;
	}

	public void setNombre2(String nombre2) {
		this.nombre2 = nombre2;
	}

	@Column(name = "apellido1", nullable = false, length = 25)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 25)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "empresa", length = 30)
	public String getEmpresa_1() {
		return this.empresa_1;
	}

	public void setEmpresa_1(String empresa_1) {
		this.empresa_1 = empresa_1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29, nullable = false)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechanacimiento", length = 29)
	public Date getFechanacimiento() {
		return fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "estadocivil")
	public int getEstadocivil() {
		return estadocivil;
	}

	public void setEstadocivil(int estadocivil) {
		this.estadocivil = estadocivil;
	}

	@Column(name = "genero")
	public int getGenero() {
		return genero;
	}

	public void setGenero(int genero) {
		this.genero = genero;
	}

	@Column(name = "idtipoidentificacion")
	public int getIdtipoidentificacion() {
		return idtipoidentificacion;
	}

	public void setIdtipoidentificacion(int idtipoidentificacion) {
		this.idtipoidentificacion = idtipoidentificacion;
	}

	@Column(name = "idtipopersona")
	public int getIdtipopersona() {
		return idtipopersona;
	}

	public void setIdtipopersona(int idtipopersona) {
		this.idtipopersona = idtipopersona;
	}

	@Column(name = "ip", length = 20)
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
	
	@Column(name = "identificacion", length = 30)
	public String getIdentificacion() {
		return identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<?> getConyuges() {
		return this.conyuges;
	}

	public void setConyuges(Set<?> conyuges) {
		this.conyuges = conyuges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<?> getCtaclientes() {
		return this.ctaclientes;
	}

	public void setCtaclientes(Set<?> ctaclientes) {
		this.ctaclientes = ctaclientes;
	}*/

}
