package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comandos generated by hbm2java
 */
@Entity
@Table(name = "comandos", schema = "public")
public class Comandos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4928604804654176204L;
	private int idcomando;
	private Controlador controlador;
	private String nombre;
	private String abreviado;
	private int idempresa;
	private int idestado;

	public Comandos() {
	}

	public Comandos(int idcomando, Controlador controlador, String nombre,
			int idempresa, int idestado) {
		this.idcomando = idcomando;
		this.controlador = controlador;
		this.nombre = nombre;
		this.idempresa = idempresa;
		this.idestado = idestado;
	}

	public Comandos(int idcomando, Controlador controlador, String nombre,
			String abreviado, int idempresa, int idestado) {
		this.idcomando = idcomando;
		this.controlador = controlador;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idempresa = idempresa;
		this.idestado = idestado;
	}

	@Id
	@Column(name = "idcomando", unique = true, nullable = false)
	public int getIdcomando() {
		return this.idcomando;
	}

	public void setIdcomando(int idcomando) {
		this.idcomando = idcomando;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcontrolador", nullable = false)
	public Controlador getControlador() {
		return this.controlador;
	}

	public void setControlador(Controlador controlador) {
		this.controlador = controlador;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 8)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

}
