package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import net.cinecable.enums.TipoEjecucionComando;
import net.cinecable.model.base.EntityBase;

/**
 * Comandos generated by hbm2java
 */
@Entity
@Table(name = "comandos", schema = "public")
public class Comandos extends EntityBase {

	private Long idcomando;
	private Controlador controlador;
	private String nombre;
	private String abreviado;
	private TipoEjecucionComando tipoComando;

	public static final int ACTIVACION = 1;
	public static final int DESACTIVACION = 2;
	public static final int BLOQUEO = 3;
	public static final int DESBLOQUEO = 4;

	@Id
	@Column(name = "idcomando", unique = true, nullable = false)
	public Long getIdcomando() {
		return this.idcomando;
	}

	public void setIdcomando(Long idcomando) {
		this.idcomando = idcomando;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcontrolador")
	public Controlador getControlador() {
		return this.controlador;
	}

	public void setControlador(Controlador controlador) {
		this.controlador = controlador;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 8)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "tipoejecucioncomando", length = 5)
	public TipoEjecucionComando getTipoComando() {
		return tipoComando;
	}

	public void setTipoComando(TipoEjecucionComando tipoComando) {
		this.tipoComando = tipoComando;
	}

}
