package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comunicacion generated by hbm2java
 */
@Entity
@Table(name = "comunicacion", schema = "public")
public class Comunicacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1002700462993554328L;
	private int idcomunicacion;
	private int idservicio;
	private int idcomando;
	private int idcuenta;
	private String respuesta;
	private String parsalida;
	private int idusuario;
	private Date fecha;
	private int idcontrolador;
	private Date fecharetorno;
	private String ip;

	public Comunicacion() {
	}

	public Comunicacion(int idcomunicacion, int idservicio, int idcomando,
			int idcuenta, int idusuario, Date fecha, int idcontrolador) {
		this.idcomunicacion = idcomunicacion;
		this.idservicio = idservicio;
		this.idcomando = idcomando;
		this.idcuenta = idcuenta;
		this.idusuario = idusuario;
		this.fecha = fecha;
		this.idcontrolador = idcontrolador;
	}

	public Comunicacion(int idcomunicacion, int idservicio, int idcomando,
			int idcuenta, String respuesta, String parsalida, int idusuario,
			Date fecha, int idcontrolador, Date fecharetorno, String ip) {
		this.idcomunicacion = idcomunicacion;
		this.idservicio = idservicio;
		this.idcomando = idcomando;
		this.idcuenta = idcuenta;
		this.respuesta = respuesta;
		this.parsalida = parsalida;
		this.idusuario = idusuario;
		this.fecha = fecha;
		this.idcontrolador = idcontrolador;
		this.fecharetorno = fecharetorno;
		this.ip = ip;
	}

	@Id
	@Column(name = "idcomunicacion", unique = true, nullable = false)
	public int getIdcomunicacion() {
		return this.idcomunicacion;
	}

	public void setIdcomunicacion(int idcomunicacion) {
		this.idcomunicacion = idcomunicacion;
	}

	@Column(name = "idservicio", nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@Column(name = "idcomando", nullable = false)
	public int getIdcomando() {
		return this.idcomando;
	}

	public void setIdcomando(int idcomando) {
		this.idcomando = idcomando;
	}

	@Column(name = "idcuenta", nullable = false)
	public int getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(int idcuenta) {
		this.idcuenta = idcuenta;
	}

	@Column(name = "respuesta", length = 1000)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Column(name = "parsalida", length = 1000)
	public String getParsalida() {
		return this.parsalida;
	}

	public void setParsalida(String parsalida) {
		this.parsalida = parsalida;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idcontrolador", nullable = false)
	public int getIdcontrolador() {
		return this.idcontrolador;
	}

	public void setIdcontrolador(int idcontrolador) {
		this.idcontrolador = idcontrolador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharetorno", length = 29)
	public Date getFecharetorno() {
		return this.fecharetorno;
	}

	public void setFecharetorno(Date fecharetorno) {
		this.fecharetorno = fecharetorno;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
