package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Control generated by hbm2java
 */
@Entity
@Table(name = "control", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idempresa", "proceso" }))
public class Control implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 670301309379149169L;
	private int idcontrol;
	private int numero;
	private Date fecha;
	private int idempresa;
	private Short proceso;

	public Control() {
	}

	public Control(int idcontrol, int numero, Date fecha, int idempresa) {
		this.idcontrol = idcontrol;
		this.numero = numero;
		this.fecha = fecha;
		this.idempresa = idempresa;
	}

	public Control(int idcontrol, int numero, Date fecha, int idempresa,
			Short proceso) {
		this.idcontrol = idcontrol;
		this.numero = numero;
		this.fecha = fecha;
		this.idempresa = idempresa;
		this.proceso = proceso;
	}

	@Id
	@Column(name = "idcontrol", unique = true, nullable = false)
	public int getIdcontrol() {
		return this.idcontrol;
	}

	public void setIdcontrol(int idcontrol) {
		this.idcontrol = idcontrol;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "proceso")
	public Short getProceso() {
		return this.proceso;
	}

	public void setProceso(Short proceso) {
		this.proceso = proceso;
	}

}
