package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Conyuge generated by hbm2java
 */
@Entity
@Table(name = "conyuge", schema = "public")
public class Conyuge implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7738032051406347728L;
	private String idconyuge;
	private Clientes clientes;
	private String nombre1;
	private String nombre2;
	private String apellido1;
	private String apellido2;
	private String identificacion;

	public Conyuge() {
	}

	public Conyuge(String idconyuge, Clientes clientes) {
		this.idconyuge = idconyuge;
		this.clientes = clientes;
	}

	public Conyuge(String idconyuge, Clientes clientes, String nombre1,
			String nombre2, String apellido1, String apellido2) {
		this.idconyuge = idconyuge;
		this.clientes = clientes;
		this.nombre1 = nombre1;
		this.nombre2 = nombre2;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
	}

	@Id
	@Column(name = "idconyuge", unique = true, nullable = false, length = 20)
	public String getIdconyuge() {
		return this.idconyuge;
	}

	public void setIdconyuge(String idconyuge) {
		this.idconyuge = idconyuge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "nombre1", length = 25)
	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	@Column(name = "nombre2", length = 25)
	public String getNombre2() {
		return this.nombre2;
	}

	public void setNombre2(String nombre2) {
		this.nombre2 = nombre2;
	}

	@Column(name = "apellido1", length = 25)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 25)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "identificacion", length = 30)
	public String getIdentificacion() {
		return identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

}
