package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Costoproducto generated by hbm2java
 */
@Entity
@Table(name = "costoproducto", schema = "public")
public class Costoproducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4934843993380150190L;
	private int idproducto;
	private Producto producto;
	private float costoproducto;
	private String ip;

	public Costoproducto() {
	}

	public Costoproducto(Producto producto, float costoproducto) {
		this.producto = producto;
		this.costoproducto = costoproducto;
	}

	public Costoproducto(Producto producto, float costoproducto, String ip) {
		this.producto = producto;
		this.costoproducto = costoproducto;
		this.ip = ip;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "producto"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idproducto", unique = true, nullable = false)
	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "costoproducto", nullable = false, precision = 8, scale = 8)
	public float getCostoproducto() {
		return this.costoproducto;
	}

	public void setCostoproducto(float costoproducto) {
		this.costoproducto = costoproducto;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
