package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Creditos generated by hbm2java
 */
@Entity
@Table(name = "creditos", schema = "public")
public class Creditos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6564710279524638352L;
	private int idcredito;
	private Estado estado;
	private Usuario usuario;
	private Empresa empresa;
	private Motivos motivos;
	private String idfactura;
	private String observaciones;
	private float vacredito;
	private Date fecha;
	private String ip;
	private int idcuenta;
	private float valrealfijo;
	private int idpago;
	
	//Atributos personalizados
	private String textoCredito;

	public Creditos() {
	}

	public Creditos(int idcredito, Estado estado, Usuario usuario,
			Empresa empresa, Motivos motivos, String idfactura,
			float vacredito, Date fecha, int idcuenta, float valrealfijo) {
		this.idcredito = idcredito;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.motivos = motivos;
		this.idfactura = idfactura;
		this.vacredito = vacredito;
		this.fecha = fecha;
		this.idcuenta = idcuenta;
		this.valrealfijo = valrealfijo;
	}

	public Creditos(int idcredito, Estado estado, Usuario usuario,
			Empresa empresa, Motivos motivos, String idfactura,
			String observaciones, float vacredito, Date fecha, String ip, int idcuenta, float valrealfijo, int idpago) {
		this.idcredito = idcredito;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.motivos = motivos;
		this.idfactura = idfactura;
		this.observaciones = observaciones;
		this.vacredito = vacredito;
		this.fecha = fecha;
		this.ip = ip;
		this.idcuenta = idcuenta;
		this.valrealfijo = valrealfijo;
		this.idpago = idpago;
	}

	@Id
	@Column(name = "idcredito", unique = true, nullable = false)
	public int getIdcredito() {
		return this.idcredito;
	}

	public void setIdcredito(int idcredito) {
		this.idcredito = idcredito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmotivo", nullable = false)
	public Motivos getMotivos() {
		return this.motivos;
	}

	public void setMotivos(Motivos motivos) {
		this.motivos = motivos;
	}

	@Column(name = "idfactura", nullable = false, length = 30)
	public String getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(String idfactura) {
		this.idfactura = idfactura;
	}

	@Column(name = "observaciones", length = 500)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "vacredito", nullable = false, precision = 8, scale = 8)
	public float getVacredito() {
		return this.vacredito;
	}

	public void setVacredito(float vacredito) {
		this.vacredito = vacredito;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
	
	@Column(name = "idcuenta", nullable = false)
	public int getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(int idcuenta) {
		this.idcuenta = idcuenta;
	}

	@Column(name = "valrealfijo", nullable = false)
	public float getValrealfijo() {
		return valrealfijo;
	}

	public void setValrealfijo(float valrealfijo) {
		this.valrealfijo = valrealfijo;
	}

	@Column(name = "idpago")
	public int getIdpago() {
		return idpago;
	}

	public void setIdpago(int idpago) {
		this.idpago = idpago;
	}

	@Transient
	public String getTextoCredito() {
		String numero = "";
		String fecha = "";
		String valor = "";
		
		if(this.idfactura != null && this.idfactura.trim().length() > 0){
			numero = this.idfactura;
		}else{
			numero = "sin número";
		}
		
		if(this.fecha != null){
			fecha =  new SimpleDateFormat("dd/MM/yyyy").format(this.fecha);
		}else{
			fecha = "sin fecha";
		}
		
		if(this.valrealfijo > 0){
			BigDecimal bd = new BigDecimal(this.valrealfijo);
			valor = bd.setScale(2, BigDecimal.ROUND_HALF_UP).toString();
		}else{
			valor = "sin valor";
		}
		
		this.textoCredito = "#" + numero + " " + fecha + " $" + valor;
		
		return textoCredito;
	}

	public void setTextoCredito(String textoCredito) {
		this.textoCredito = textoCredito;
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empresa == null) ? 0 : empresa.getIdempresa());
		result = prime * result + ((estado == null) ? 0 : estado.getIdestado());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result + idcredito;
		result = prime * result + idcuenta;
		result = prime * result
				+ ((idfactura == null) ? 0 : idfactura.hashCode());
		result = prime * result + idpago;
		result = prime * result + ((ip == null) ? 0 : ip.hashCode());
		result = prime * result + ((motivos == null) ? 0 : motivos.getIdmotivo());
		result = prime * result
				+ ((observaciones == null) ? 0 : observaciones.hashCode());
		result = prime * result + ((usuario == null) ? 0 : usuario.getIdusuario());
		result = prime * result + Float.floatToIntBits(vacredito);
		result = prime * result + Float.floatToIntBits(valrealfijo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Creditos other = (Creditos) obj;
		if (empresa == null) {
			if (other.empresa != null)
				return false;
		} else if (empresa.getIdempresa() != other.empresa.getIdempresa())
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
		} else if (estado.getIdestado() != other.estado.getIdestado())
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (idcredito != other.idcredito)
			return false;
		if (idcuenta != other.idcuenta)
			return false;
		if (idfactura == null) {
			if (other.idfactura != null)
				return false;
		} else if (!idfactura.equals(other.idfactura))
			return false;
		if (idpago != other.idpago)
			return false;
		if (ip == null) {
			if (other.ip != null)
				return false;
		} else if (!ip.equals(other.ip))
			return false;
		if (motivos == null) {
			if (other.motivos != null)
				return false;
		} else if (motivos.getIdmotivo() != other.motivos.getIdmotivo())
			return false;
		if (observaciones == null) {
			if (other.observaciones != null)
				return false;
		} else if (!observaciones.equals(other.observaciones))
			return false;
		if (usuario == null) {
			if (other.usuario != null)
				return false;
		} else if (usuario.getIdusuario() != other.usuario.getIdusuario())
			return false;
		if (Float.floatToIntBits(vacredito) != Float
				.floatToIntBits(other.vacredito))
			return false;
		if (Float.floatToIntBits(valrealfijo) != Float
				.floatToIntBits(other.valrealfijo))
			return false;
		return true;
	}
	
	
}
