package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cronograma generated by hbm2java
 */
@Entity
@Table(name = "cronograma", schema = "public")
public class Cronograma implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3390743046721816510L;
	private int idcronograma;
	private short dia;
	private short mes;
	private short anio;
	private short cantidad;
	private short ocupados;
	private int idtipooperacion;
	private int idusuario;
	private Date fecha;
	private int diferencia;

	public Cronograma() {
	}

	public Cronograma(int idcronograma, short dia, short mes, short anio,
			short cantidad, short ocupados, int idtipooperacion, int idusuario,
			Date fecha, int diferencia) {
		this.idcronograma = idcronograma;
		this.dia = dia;
		this.mes = mes;
		this.anio = anio;
		this.cantidad = cantidad;
		this.ocupados = ocupados;
		this.idtipooperacion = idtipooperacion;
		this.idusuario = idusuario;
		this.fecha = fecha;
		this.diferencia = diferencia;
	}

	@Id
	@Column(name = "idcronograma", unique = true, nullable = false)
	public int getIdcronograma() {
		return this.idcronograma;
	}

	public void setIdcronograma(int idcronograma) {
		this.idcronograma = idcronograma;
	}

	@Column(name = "dia", nullable = false)
	public short getDia() {
		return this.dia;
	}

	public void setDia(short dia) {
		this.dia = dia;
	}

	@Column(name = "mes", nullable = false)
	public short getMes() {
		return this.mes;
	}

	public void setMes(short mes) {
		this.mes = mes;
	}

	@Column(name = "anio", nullable = false)
	public short getAnio() {
		return this.anio;
	}

	public void setAnio(short anio) {
		this.anio = anio;
	}

	@Column(name = "cantidad", nullable = false)
	public short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(short cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "ocupados", nullable = false)
	public short getOcupados() {
		return this.ocupados;
	}

	public void setOcupados(short ocupados) {
		this.ocupados = ocupados;
	}

	@Column(name = "idtipooperacion", nullable = false)
	public int getIdtipooperacion() {
		return this.idtipooperacion;
	}

	public void setIdtipooperacion(int idtipooperacion) {
		this.idtipooperacion = idtipooperacion;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "diferencia", nullable = false)
	public int getDiferencia() {
		return this.diferencia;
	}

	public void setDiferencia(int diferencia) {
		this.diferencia = diferencia;
	}

}
