package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ctasprod generated by hbm2java
 */
@Entity
@Table(name = "ctasprod", schema = "public")
public class Ctasprod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6903323071826347459L;
	private int idprodcuentas;
	private Estado estado;
	private Ctacliente ctacliente;
	private Empresa empresa;
	private Producto producto;
	private Date finstalacion;

	public Ctasprod() {
	}

	public Ctasprod(int idprodcuentas, Estado estado, Ctacliente ctacliente,
			Empresa empresa, Producto producto) {
		this.idprodcuentas = idprodcuentas;
		this.estado = estado;
		this.ctacliente = ctacliente;
		this.empresa = empresa;
		this.producto = producto;
	}

	public Ctasprod(int idprodcuentas, Estado estado, Ctacliente ctacliente,
			Empresa empresa, Producto producto, Date finstalacion) {
		this.idprodcuentas = idprodcuentas;
		this.estado = estado;
		this.ctacliente = ctacliente;
		this.empresa = empresa;
		this.producto = producto;
		this.finstalacion = finstalacion;
	}

	@Id
	@Column(name = "idprodcuentas", unique = true, nullable = false)
	public int getIdprodcuentas() {
		return this.idprodcuentas;
	}

	public void setIdprodcuentas(int idprodcuentas) {
		this.idprodcuentas = idprodcuentas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuenta", nullable = false)
	public Ctacliente getCtacliente() {
		return this.ctacliente;
	}

	public void setCtacliente(Ctacliente ctacliente) {
		this.ctacliente = ctacliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finstalacion", length = 13)
	public Date getFinstalacion() {
		return this.finstalacion;
	}

	public void setFinstalacion(Date finstalacion) {
		this.finstalacion = finstalacion;
	}

}
