package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Debitobco generated by hbm2java
 */
@Entity
@Table(name = "debitobco", schema = "public")
public class Debitobco implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -675806293271550648L;
	private int iddebitobco;
	private Bancos bancos;
	private int idtipodebito;
	private int idtipoidentificacion;
	private int idtipocuenta;
	private String identificacion;
	private Date fcaducidad;
	private String codigoseguridad;
	private String propietario;
	private Integer idbancotar;
	private String nrodebito;
	//private Set<?> ctaclientes = new HashSet<Object>(0);

	public Debitobco() {
	}

	public Debitobco(int iddebitobco, int idtipodebito) {
		this.iddebitobco = iddebitobco;
		this.idtipodebito = idtipodebito;
	}

	public Debitobco(int iddebitobco, Bancos bancos, int idtipodebito,
			Date fcaducidad, String codigoseguridad, String propietario,
			Integer idbancotar, String nrodebito/*, Set<?> ctaclientes*/) {
		this.iddebitobco = iddebitobco;
		this.bancos = bancos;
		this.idtipodebito = idtipodebito;
		this.fcaducidad = fcaducidad;
		this.codigoseguridad = codigoseguridad;
		this.propietario = propietario;
		this.idbancotar = idbancotar;
		this.nrodebito = nrodebito;
		//this.ctaclientes = ctaclientes;
	}

	@Id
	@Column(name = "iddebitobco", unique = true, nullable = false)
	public int getIddebitobco() {
		return this.iddebitobco;
	}

	public void setIddebitobco(int iddebitobco) {
		this.iddebitobco = iddebitobco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbanco")
	public Bancos getBancos() {
		return this.bancos;
	}

	public void setBancos(Bancos bancos) {
		this.bancos = bancos;
	}

	@Column(name = "idtipodebito", nullable = false)
	public int getIdtipodebito() {
		return this.idtipodebito;
	}

	public void setIdtipodebito(int idtipodebito) {
		this.idtipodebito = idtipodebito;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fcaducidad", length = 13)
	public Date getFcaducidad() {
		return this.fcaducidad;
	}

	public void setFcaducidad(Date fcaducidad) {
		this.fcaducidad = fcaducidad;
	}

	@Column(name = "codigoseguridad", length = 50)
	public String getCodigoseguridad() {
		return this.codigoseguridad;
	}

	public void setCodigoseguridad(String codigoseguridad) {
		this.codigoseguridad = codigoseguridad;
	}

	@Column(name = "propietario", length = 25)
	public String getPropietario() {
		return this.propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	@Column(name = "idbancotar")
	public Integer getIdbancotar() {
		return this.idbancotar;
	}

	public void setIdbancotar(Integer idbancotar) {
		this.idbancotar = idbancotar;
	}

	@Column(name = "nrodebito", length = 20)
	public String getNrodebito() {
		return this.nrodebito;
	}

	public void setNrodebito(String nrodebito) {
		this.nrodebito = nrodebito;
	}

	@Column(name = "idtipoidentificacion")
	public int getIdtipoidentificacion() {
		return idtipoidentificacion;
	}

	public void setIdtipoidentificacion(int idtipoidentificacion) {
		this.idtipoidentificacion = idtipoidentificacion;
	}
	
	@Column(name = "idtipocuenta")
	public int getIdtipocuenta() {
		return idtipocuenta;
	}

	public void setIdtipocuenta(int idtipocuenta) {
		this.idtipocuenta = idtipocuenta;
	}
	
	@Column(name = "identificacion")
	public String getIdentificacion() {
		return identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "debitobco")
	public Set<?> getCtaclientes() {
		return this.ctaclientes;
	}

	public void setCtaclientes(Set<?> ctaclientes) {
		this.ctaclientes = ctaclientes;
	}*/

}
