package pojo.annotations;

// Generated 13/03/2014 06:57:41 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Detimpfacturas generated by hbm2java
 */
@Entity
@Table(name = "detimpfacturas", schema = "public")
public class Detimpfacturas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2669134215505792906L;
	private int iddetfacturas;
	private Integer idcabfacturas;
	private String detalle;
	private Float valor;
	private Integer orden;
	private Integer idcuenta;
	private Integer idempresa;
	private Integer idestado;

	public Detimpfacturas() {
	}

	public Detimpfacturas(int iddetfacturas) {
		this.iddetfacturas = iddetfacturas;
	}

	public Detimpfacturas(int iddetfacturas, Integer idcabfacturas,
			String detalle, Float valor, Integer orden, Integer idcuenta,
			Integer idempresa, Integer idestado) {
		this.iddetfacturas = iddetfacturas;
		this.idcabfacturas = idcabfacturas;
		this.detalle = detalle;
		this.valor = valor;
		this.orden = orden;
		this.idcuenta = idcuenta;
		this.idempresa = idempresa;
		this.idestado = idestado;
	}

	@Id
	@Column(name = "iddetfacturas", unique = true, nullable = false)
	public int getIddetfacturas() {
		return this.iddetfacturas;
	}

	public void setIddetfacturas(int iddetfacturas) {
		this.iddetfacturas = iddetfacturas;
	}

	@Column(name = "idcabfacturas")
	public Integer getIdcabfacturas() {
		return this.idcabfacturas;
	}

	public void setIdcabfacturas(Integer idcabfacturas) {
		this.idcabfacturas = idcabfacturas;
	}

	@Column(name = "detalle", length = 50)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "valor", precision = 8, scale = 8)
	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "idcuenta")
	public Integer getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(Integer idcuenta) {
		this.idcuenta = idcuenta;
	}

	@Column(name = "idempresa")
	public Integer getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(Integer idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "idestado")
	public Integer getIdestado() {
		return this.idestado;
	}

	public void setIdestado(Integer idestado) {
		this.idestado = idestado;
	}

}
