package pojo.annotations;

// Generated 09-feb-2014 10:19:46 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.Table;


/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", schema = "public")
public class Direccion implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 21333028665661038L;
	private int iddireccion;
	private Edificio edificio;
	private Referenciadir referenciadir;
	private Ctacliente ctacliente;
	private Calleprincipal calleprincipal;
	private Tiposector tiposector;
	private Callesecundaria callesecundaria;
	private Ubicacion ubicacion;
	private Nodos nodos;
	private Sector sector;
	private Integer numero;
	private Integer piso;
	private Integer departamento;
	private String idtab;
	private String correspondencia;
	private String vineta;
	private String poste;
	private String solar;
	private int idtipodireccion;
	private Estado estado;
	
	public Direccion() {
	}

	public Direccion(int iddireccion, Ctacliente ctacliente,
			Tiposector tiposector, Nodos nodos, Sector sector,
			String correspondencia, String vineta) {
		this.iddireccion = iddireccion;
		this.ctacliente = ctacliente;
		this.tiposector = tiposector;
		this.nodos = nodos;
		this.sector = sector;
		this.correspondencia = correspondencia;
		this.vineta = vineta;
	}

	public Direccion(int iddireccion, Edificio edificio, Ctacliente ctacliente,
			Calleprincipal calleprincipal, Tiposector tiposector,
			Callesecundaria callesecundaria, Ubicacion ubicacion, Nodos nodos,
			Sector sector, Integer numero, Integer piso, Integer departamento,
			String idtab, String correspondencia, String vineta, String poste,
			String solar) {
		this.iddireccion = iddireccion;
		this.edificio = edificio;
		this.ctacliente = ctacliente;
		this.calleprincipal = calleprincipal;
		this.tiposector = tiposector;
		this.callesecundaria = callesecundaria;
		this.ubicacion = ubicacion;
		this.nodos = nodos;
		this.sector = sector;
		this.numero = numero;
		this.piso = piso;
		this.departamento = departamento;
		this.idtab = idtab;
		this.correspondencia = correspondencia;
		this.vineta = vineta;
		this.poste = poste;
		this.solar = solar;
	}
	
	@Column(name = "idtipodireccion")
	public int getIdtipodireccion() {
		return idtipodireccion;
	}

	public void setIdtipodireccion(int idtipodireccion) {
		this.idtipodireccion = idtipodireccion;
	}
	
	@Id
	@Column(name = "iddireccion", unique = true, nullable = false)
	/* @SequenceGenerator(name = "sq_generacion_direccion", sequenceName = "sq_generacion_direccion", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sq_generacion_direccion") */
	public int getIddireccion() {
		return this.iddireccion;
	}

	public void setIddireccion(int iddireccion) {
		this.iddireccion = iddireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idedificio")
	public Edificio getEdificio() {
		return this.edificio;
	}

	public void setEdificio(Edificio edificio) {
		this.edificio = edificio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuenta", nullable = false)
	public Ctacliente getCtacliente() {
		return this.ctacliente;
	}

	public void setCtacliente(Ctacliente ctacliente) {
		this.ctacliente = ctacliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcalleprincipal")
	public Calleprincipal getCalleprincipal() {
		return this.calleprincipal;
	}

	public void setCalleprincipal(Calleprincipal calleprincipal) {
		this.calleprincipal = calleprincipal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtiposector", nullable = false)
	public Tiposector getTiposector() {
		return this.tiposector;
	}

	public void setTiposector(Tiposector tiposector) {
		this.tiposector = tiposector;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcallesecundaria")
	public Callesecundaria getCallesecundaria() {
		return this.callesecundaria;
	}

	public void setCallesecundaria(Callesecundaria callesecundaria) {
		this.callesecundaria = callesecundaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idubicacion")
	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idnodo", nullable = false)
	public Nodos getNodos() {
		return this.nodos;
	}

	public void setNodos(Nodos nodos) {
		this.nodos = nodos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsector", nullable = false)
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "piso")
	public Integer getPiso() {
		return this.piso;
	}

	public void setPiso(Integer piso) {
		this.piso = piso;
	}

	@Column(name = "departamento")
	public Integer getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Integer departamento) {
		this.departamento = departamento;
	}

	@Column(name = "idtab")
	public String getIdtab() {
		return this.idtab;
	}

	public void setIdtab(String idtab) {
		this.idtab = idtab;
	}

	@Column(name = "correspondencia", nullable = false, length = 1)
	public String getCorrespondencia() {
		return this.correspondencia;
	}

	public void setCorrespondencia(String correspondencia) {
		this.correspondencia = correspondencia;
	}

	@Column(name = "vineta", nullable = false, length = 12)
	public String getVineta() {
		return this.vineta;
	}

	public void setVineta(String vineta) {
		this.vineta = vineta;
	}

	@Column(name = "poste", length = 6)
	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	@Column(name = "solar", length = 10)
	public String getSolar() {
		return this.solar;
	}

	public void setSolar(String solar) {
		this.solar = solar;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idreferencia")
	public Referenciadir getReferenciadir() {
		return referenciadir;
	}

	public void setReferenciadir(Referenciadir referenciadir) {
		this.referenciadir = referenciadir;
	}

	
	@ManyToOne
	@JoinColumn(name = "idestado")
	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}
	@Override
	protected Object clone() throws CloneNotSupportedException {
		Direccion direccion = (Direccion) super.clone();
		
			
		return direccion;
	}
	
	public Direccion clonar() throws Exception {
		return (Direccion)this.clone();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((calleprincipal == null) ? 0 : calleprincipal.getIdcalleprincipal());
		result = prime * result
				+ ((callesecundaria == null) ? 0 : callesecundaria.getIdcallesecundaria());
		result = prime * result
				+ ((correspondencia == null) ? 0 : correspondencia.hashCode());
		result = prime * result
				+ ((ctacliente == null) ? 0 : ctacliente.getIdcuenta());
		result = prime * result
				+ ((departamento == null) ? 0 : departamento.hashCode());
		result = prime * result
				+ ((edificio == null) ? 0 : edificio.getIdedificio());
		result = prime * result + iddireccion;
		result = prime * result + ((estado == null) ? 0 : estado.getIdestado());
		result = prime * result + ((idtab == null) ? 0 : idtab.hashCode());
		result = prime * result + ((nodos == null) ? 0 : nodos.getIdnodo());
		result = prime * result + ((numero == null) ? 0 : numero.hashCode());
		result = prime * result + ((piso == null) ? 0 : piso.hashCode());
		result = prime * result + ((poste == null) ? 0 : poste.hashCode());
		result = prime * result + ((sector == null) ? 0 : sector.getIdsector());
		result = prime * result + ((solar == null) ? 0 : solar.hashCode());
		result = prime * result
				+ ((tiposector == null) ? 0 : tiposector.getIdtiposector());
		result = prime * result
				+ ((ubicacion == null) ? 0 : ubicacion.getIdubicacion());
		result = prime * result + ((vineta == null) ? 0 : vineta.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Direccion other = (Direccion) obj;
		if (calleprincipal == null) {
			if (other.calleprincipal != null)
				return false;
		} else if (calleprincipal.getIdcalleprincipal() != other.calleprincipal.getIdcalleprincipal())
			return false;
		if (callesecundaria == null) {
			if (other.callesecundaria != null)
				return false;
		} else if (callesecundaria.getIdcallesecundaria() != other.callesecundaria.getIdcallesecundaria())
			return false;
		if (correspondencia == null) {
			if (other.correspondencia != null)
				return false;
		} else if (!correspondencia.equals(other.correspondencia))
			return false;
		if (ctacliente == null) {
			if (other.ctacliente != null)
				return false;
		} else if (ctacliente.getIdcuenta() != other.ctacliente.getIdcuenta())
			return false;
		if (departamento == null) {
			if (other.departamento != null)
				return false;
		} else if (!departamento.equals(other.departamento))
			return false;
		if (edificio == null) {
			if (other.edificio != null)
				return false;
		} else if (edificio.getIdedificio() != other.edificio.getIdedificio())
			return false;
		if (iddireccion != other.iddireccion)
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
	   } else if (idtab == null) {
			if (other.idtab != null)
				return false;
		} else if (!idtab.equals(other.idtab))
			return false;
		if (nodos == null) {
			if (other.nodos != null)
				return false;
		} else if (nodos.getIdnodo() != other.nodos.getIdnodo())
			return false;
		if (numero == null) {
			if (other.numero != null)
				return false;
		} else if (!numero.equals(other.numero))
			return false;
		if (piso == null) {
			if (other.piso != null)
				return false;
		} else if (!piso.equals(other.piso))
			return false;
		if (poste == null) {
			if (other.poste != null)
				return false;
		} else if (!poste.equals(other.poste))
			return false;
		if (sector == null) {
			if (other.sector != null)
				return false;
		} else if (sector.getIdsector() != other.sector.getIdsector())
			return false;
		if (solar == null) {
			if (other.solar != null)
				return false;
		} else if (!solar.equals(other.solar))
			return false;
		if (tiposector == null) {
			if (other.tiposector != null)
				return false;
		} else if (tiposector.getIdtiposector() != other.tiposector.getIdtiposector())
			return false;
		if (ubicacion == null) {
			if (other.ubicacion != null)
				return false;
		} else if (ubicacion.getIdubicacion() != other.ubicacion.getIdubicacion())
			return false;
		if (vineta == null) {
			if (other.vineta != null)
				return false;
		} else if (!vineta.equals(other.vineta))
			return false;
		return true;
	}
	
	

}
