package pojo.annotations;

// Generated 09-feb-2014 10:19:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Edificio generated by hbm2java
 */
@Entity
@Table(name = "edificio", schema = "public")
public class Edificio implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idedificio;
	private Estado estado;
	private Sector sector;
	private Usuario usuario;
	private String nombre;
	private String abreviado;
	private Date fecha;
	private Set<?> direccions = new HashSet<Object>(0);

	public Edificio() {
	}

	public Edificio(int idedificio, Estado estado, Sector sector,
			Usuario usuario, String nombre, Date fecha) {
		this.idedificio = idedificio;
		this.estado = estado;
		this.sector = sector;
		this.usuario = usuario;
		this.nombre = nombre;
		this.fecha = fecha;
	}

	public Edificio(int idedificio, Estado estado, Sector sector,
			Usuario usuario, String nombre, String abreviado, Date fecha,
			Set<?> direccions) {
		this.idedificio = idedificio;
		this.estado = estado;
		this.sector = sector;
		this.usuario = usuario;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.fecha = fecha;
		this.direccions = direccions;
	}

	@Id
	@Column(name = "idedificio", unique = true, nullable = false)
	public int getIdedificio() {
		return this.idedificio;
	}

	public void setIdedificio(int idedificio) {
		this.idedificio = idedificio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsector", nullable = false)
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "edificio",targetEntity=Direccion.class)
	public Set<?> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<?> direccions) {
		this.direccions = direccions;
	}
	
	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

}
