package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", schema = "public")
public class Empresa implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7547370608487695287L;
	private int idempresa;
	private String nombre;
	private String abreviado;
	private int idestado;
	private int idciudad;
	private int idusuario;
	private Date fecha;
	/*private Set<?> productos = new HashSet<Object>(0);
	private Set<?> ctaclientes = new HashSet<Object>(0);
	private Set<?> cargoses = new HashSet<Object>(0);
	private Set<?> clienteses = new HashSet<Object>(0);
	private Set<?> usuarios = new HashSet<Object>(0);
	private Set<?> creditoses = new HashSet<Object>(0);
	private Set<?> ctasprods = new HashSet<Object>(0);
	private Set<?> bancoses = new HashSet<Object>(0);
	private Set<?> tipoclientes = new HashSet<Object>(0);
	private Set<?> facturas = new HashSet<Object>(0);
	private Set<?> callesecundarias = new HashSet<Object>(0);
	private Set<?> motivoses = new HashSet<Object>(0);
	private Set<?> pagoses = new HashSet<Object>(0);
	private Set<?> sectors = new HashSet<Object>(0);
	private Set<?> areas = new HashSet<Object>(0);*/

	public Empresa() {
	}

	public Empresa(int idempresa, String nombre, int idestado, int idciudad,
			int idusuario) {
		this.idempresa = idempresa;
		this.nombre = nombre;
		this.idestado = idestado;
		this.idciudad = idciudad;
		this.idusuario = idusuario;
	}

	public Empresa(int idempresa, String nombre, String abreviado,
			int idestado, int idciudad, int idusuario, Date fecha/*,
			Set<?> productos, Set<?> ctaclientes, Set<?> cargoses, Set<?> clienteses,
			Set<?> usuarios, Set<?> creditoses, Set<?> ctasprods, Set<?> bancoses,
			Set<?> tipoclientes, Set<?> facturas, Set<?> callesecundarias,
			Set<?> motivoses, Set<?> pagoses, Set<?> sectors, Set<?> areas*/) {
		this.idempresa = idempresa;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idestado = idestado;
		this.idciudad = idciudad;
		this.idusuario = idusuario;
		this.fecha = fecha;
		/*this.productos = productos;
		this.ctaclientes = ctaclientes;
		this.cargoses = cargoses;
		this.clienteses = clienteses;
		this.usuarios = usuarios;
		this.creditoses = creditoses;
		this.ctasprods = ctasprods;
		this.bancoses = bancoses;
		this.tipoclientes = tipoclientes;
		this.facturas = facturas;
		this.callesecundarias = callesecundarias;
		this.motivoses = motivoses;
		this.pagoses = pagoses;
		this.sectors = sectors;
		this.areas = areas;*/
	}

	@Id
	@Column(name = "idempresa", unique = true, nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idciudad", nullable = false)
	public int getIdciudad() {
		return this.idciudad;
	}

	public void setIdciudad(int idciudad) {
		this.idciudad = idciudad;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<?> productos) {
		this.productos = productos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getCtaclientes() {
		return this.ctaclientes;
	}

	public void setCtaclientes(Set<?> ctaclientes) {
		this.ctaclientes = ctaclientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getCargoses() {
		return this.cargoses;
	}

	public void setCargoses(Set<?> cargoses) {
		this.cargoses = cargoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<?> clienteses) {
		this.clienteses = clienteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<?> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getCreditoses() {
		return this.creditoses;
	}

	public void setCreditoses(Set<?> creditoses) {
		this.creditoses = creditoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getCtasprods() {
		return this.ctasprods;
	}

	public void setCtasprods(Set<?> ctasprods) {
		this.ctasprods = ctasprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getBancoses() {
		return this.bancoses;
	}

	public void setBancoses(Set<?> bancoses) {
		this.bancoses = bancoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getTipoclientes() {
		return this.tipoclientes;
	}

	public void setTipoclientes(Set<?> tipoclientes) {
		this.tipoclientes = tipoclientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<?> facturas) {
		this.facturas = facturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getCallesecundarias() {
		return this.callesecundarias;
	}

	public void setCallesecundarias(Set<?> callesecundarias) {
		this.callesecundarias = callesecundarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getMotivoses() {
		return this.motivoses;
	}

	public void setMotivoses(Set<?> motivoses) {
		this.motivoses = motivoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getPagoses() {
		return this.pagoses;
	}

	public void setPagoses(Set<?> pagoses) {
		this.pagoses = pagoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getSectors() {
		return this.sectors;
	}

	public void setSectors(Set<?> sectors) {
		this.sectors = sectors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<?> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<?> areas) {
		this.areas = areas;
	}*/

}
