package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", schema = "public")
public class Estado implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3283586921381875140L;
	private int idestado;
	private String nombre;
	private String abreviado;
	/*private Set<?> tipoclientes = new HashSet<Object>(0);
	private Set<?> telefonos = new HashSet<Object>(0);
	private Set<?> productos = new HashSet<Object>(0);
	private Set<?> ciudads = new HashSet<Object>(0);
	private Set<?> edificios = new HashSet<Object>(0);
	private Set<?> pagoses = new HashSet<Object>(0);
	private Set<?> calleprincipals = new HashSet<Object>(0);
	private Set<?> cargoses = new HashSet<Object>(0);
	private Set<?> creditoses = new HashSet<Object>(0);
	private Set<?> bancoses = new HashSet<Object>(0);
	private Set<?> callesecundarias = new HashSet<Object>(0);
	private Set<?> sectors = new HashSet<Object>(0);
	private Set<?> areas = new HashSet<Object>(0);
	private Set<?> ctasprods = new HashSet<Object>(0);
	private Set<?> motivoses = new HashSet<Object>(0);*/

	public Estado() {
	}

	public Estado(int idestado, String nombre) {
		this.idestado = idestado;
		this.nombre = nombre;
	}

	public Estado(int idestado, String nombre, String abreviado/*,
			Set<?> tipoclientes, Set<?> telefonos, Set<?> productos, Set<?> ciudads,
			Set<?> edificios, Set<?> pagoses, Set<?> calleprincipals, Set<?> cargoses,
			Set<?> creditoses, Set<?> bancoses, Set<?> callesecundarias, Set<?> sectors,
			Set<?> areas, Set<?> ctasprods, Set<?> motivoses*/) {
		this.idestado = idestado;
		this.nombre = nombre;
		this.abreviado = abreviado;
		/*this.tipoclientes = tipoclientes;
		this.telefonos = telefonos;
		this.productos = productos;
		this.ciudads = ciudads;
		this.edificios = edificios;
		this.pagoses = pagoses;
		this.calleprincipals = calleprincipals;
		this.cargoses = cargoses;
		this.creditoses = creditoses;
		this.bancoses = bancoses;
		this.callesecundarias = callesecundarias;
		this.sectors = sectors;
		this.areas = areas;
		this.ctasprods = ctasprods;
		this.motivoses = motivoses;*/
	}

	@Id
	@Column(name = "idestado", unique = true, nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}
	
	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getTipoclientes() {
		return this.tipoclientes;
	}

	public void setTipoclientes(Set<?> tipoclientes) {
		this.tipoclientes = tipoclientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(Set<?> telefonos) {
		this.telefonos = telefonos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<?> productos) {
		this.productos = productos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<?> ciudads) {
		this.ciudads = ciudads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getEdificios() {
		return this.edificios;
	}

	public void setEdificios(Set<?> edificios) {
		this.edificios = edificios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getPagoses() {
		return this.pagoses;
	}

	public void setPagoses(Set<?> pagoses) {
		this.pagoses = pagoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getCalleprincipals() {
		return this.calleprincipals;
	}

	public void setCalleprincipals(Set<?> calleprincipals) {
		this.calleprincipals = calleprincipals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getCargoses() {
		return this.cargoses;
	}

	public void setCargoses(Set<?> cargoses) {
		this.cargoses = cargoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getCreditoses() {
		return this.creditoses;
	}

	public void setCreditoses(Set<?> creditoses) {
		this.creditoses = creditoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getBancoses() {
		return this.bancoses;
	}

	public void setBancoses(Set<?> bancoses) {
		this.bancoses = bancoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getCallesecundarias() {
		return this.callesecundarias;
	}

	public void setCallesecundarias(Set<?> callesecundarias) {
		this.callesecundarias = callesecundarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getSectors() {
		return this.sectors;
	}

	public void setSectors(Set<?> sectors) {
		this.sectors = sectors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<?> areas) {
		this.areas = areas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getCtasprods() {
		return this.ctasprods;
	}

	public void setCtasprods(Set<?> ctasprods) {
		this.ctasprods = ctasprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<?> getMotivoses() {
		return this.motivoses;
	}

	public void setMotivoses(Set<?> motivoses) {
		this.motivoses = motivoses;
	}*/

}
