package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", schema = "public")
public class Evento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1125354343451542529L;
	private int idevento;
	private String titulo;
	private String descripcion;
	private Date fechadesde;
	private Date fechahasta;
	private Date fecharegistro;
	private String iplog;
	private int idestado;
	private int idusuario;
	private int idempresa;

	public Evento() {
	}

	public Evento(int idevento, String titulo, Date fechadesde,
			Date fechahasta, Date fecharegistro, int idestado, int idusuario,
			int idempresa) {
		this.idevento = idevento;
		this.titulo = titulo;
		this.fechadesde = fechadesde;
		this.fechahasta = fechahasta;
		this.fecharegistro = fecharegistro;
		this.idestado = idestado;
		this.idusuario = idusuario;
		this.idempresa = idempresa;
	}

	public Evento(int idevento, String titulo, String descripcion,
			Date fechadesde, Date fechahasta, Date fecharegistro, String iplog,
			int idestado, int idusuario, int idempresa) {
		this.idevento = idevento;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.fechadesde = fechadesde;
		this.fechahasta = fechahasta;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.idestado = idestado;
		this.idusuario = idusuario;
		this.idempresa = idempresa;
	}

	@Id
	@Column(name = "idevento", unique = true, nullable = false)
	public int getIdevento() {
		return this.idevento;
	}

	public void setIdevento(int idevento) {
		this.idevento = idevento;
	}

	@Column(name = "titulo", nullable = false, length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", length = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechadesde", nullable = false, length = 29)
	public Date getFechadesde() {
		return this.fechadesde;
	}

	public void setFechadesde(Date fechadesde) {
		this.fechadesde = fechadesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahasta", nullable = false, length = 29)
	public Date getFechahasta() {
		return this.fechahasta;
	}

	public void setFechahasta(Date fechahasta) {
		this.fechahasta = fechahasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

}
