package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Excedentes generated by hbm2java
 */
@Entity
@Table(name = "excedentes", schema = "public")
public class Excedentes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7153351249410778353L;
	private int idexcedente;
	private float valpago;
	private int idfpago;
	private String nrodocumento;
	private Integer idbcoemisor;
	private Integer idbcoemisortar;
	private Date fcaducidad;
	private String codseguridad;
	private String propietario;
	private String nrocuenta;
	private int idestado;
	private Integer idempresa;
	private int idcuenta;
	private float valpendiente;
	private Date fecha;
	private String ip;
	private int idusuario;
	private int idpago;
	
	//Atributos personalizados
	private String textoExcedentes;

	public Excedentes() {
	}

	public Excedentes(int idexcedente, float valpago, int idfpago, int idestado, int idcuenta, float valpendiente, Date fecha, int idusuario) {
		this.idexcedente = idexcedente;
		this.valpago = valpago;
		this.idfpago = idfpago;
		this.idestado = idestado;
		this.idcuenta = idcuenta;
		this.valpendiente = valpendiente;
		this.fecha = fecha;
		this.idusuario = idusuario;
	}

	public Excedentes(int idexcedente, float valpago, int idfpago,
			String nrodocumento, Integer idbcoemisor, Integer idbcoemisortar,
			Date fcaducidad, String codseguridad, String propietario,
			String nrocuenta, int idestado, Integer idempresa, int idcuenta, float valpendiente, Date fecha, String ip, int idusuario, int idpago) {
		this.idexcedente = idexcedente;
		this.valpago = valpago;
		this.idfpago = idfpago;
		this.nrodocumento = nrodocumento;
		this.idbcoemisor = idbcoemisor;
		this.idbcoemisortar = idbcoemisortar;
		this.fcaducidad = fcaducidad;
		this.codseguridad = codseguridad;
		this.propietario = propietario;
		this.nrocuenta = nrocuenta;
		this.idestado = idestado;
		this.idempresa = idempresa;
		this.idcuenta = idcuenta;
		this.valpendiente = valpendiente;
		this.fecha = fecha;
		this.ip = ip;
		this.idusuario = idusuario;
		this.idpago = idpago;
	}

	@Id
	@Column(name = "idexcedente", unique = true, nullable = false)
	public int getIdexcedente() {
		return this.idexcedente;
	}

	public void setIdexcedente(int idexcedente) {
		this.idexcedente = idexcedente;
	}

	@Column(name = "valpago", nullable = false, precision = 8, scale = 8)
	public float getValpago() {
		return this.valpago;
	}

	public void setValpago(float valpago) {
		this.valpago = valpago;
	}

	@Column(name = "idfpago", nullable = false)
	public int getIdfpago() {
		return this.idfpago;
	}

	public void setIdfpago(int idfpago) {
		this.idfpago = idfpago;
	}

	@Column(name = "nrodocumento", length = 30)
	public String getNrodocumento() {
		return this.nrodocumento;
	}

	public void setNrodocumento(String nrodocumento) {
		this.nrodocumento = nrodocumento;
	}

	@Column(name = "idbcoemisor")
	public Integer getIdbcoemisor() {
		return this.idbcoemisor;
	}

	public void setIdbcoemisor(Integer idbcoemisor) {
		this.idbcoemisor = idbcoemisor;
	}

	@Column(name = "idbcoemisortar")
	public Integer getIdbcoemisortar() {
		return this.idbcoemisortar;
	}

	public void setIdbcoemisortar(Integer idbcoemisortar) {
		this.idbcoemisortar = idbcoemisortar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fcaducidad", length = 13)
	public Date getFcaducidad() {
		return this.fcaducidad;
	}

	public void setFcaducidad(Date fcaducidad) {
		this.fcaducidad = fcaducidad;
	}

	@Column(name = "codseguridad", length = 8)
	public String getCodseguridad() {
		return this.codseguridad;
	}

	public void setCodseguridad(String codseguridad) {
		this.codseguridad = codseguridad;
	}

	@Column(name = "propietario", length = 30)
	public String getPropietario() {
		return this.propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	@Column(name = "nrocuenta", length = 20)
	public String getNrocuenta() {
		return this.nrocuenta;
	}

	public void setNrocuenta(String nrocuenta) {
		this.nrocuenta = nrocuenta;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idempresa")
	public Integer getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(Integer idempresa) {
		this.idempresa = idempresa;
	}
	
	@Column(name = "idcuenta", nullable = false)
	public int getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(int idcuenta) {
		this.idcuenta = idcuenta;
	}

	@Column(name = "valpendiente", precision = 8, scale = 8)
	public float getValpendiente() {
		return valpendiente;
	}

	public void setValpendiente(float valpendiente) {
		this.valpendiente = valpendiente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idpago")
	public int getIdpago() {
		return idpago;
	}

	public void setIdpago(int idpago) {
		this.idpago = idpago;
	}

	@Transient
	public String getTextoExcedentes() {
		String numero = "";
		String fecha = "";
		String valor = "";
		
		if(this.nrodocumento != null && this.nrodocumento.trim().length() > 0){
			numero = this.nrodocumento;
		}else{
			numero = "sin numero";
		}
		
		if(this.fecha != null){
			fecha =  new SimpleDateFormat("dd/MM/yyyy").format(this.fecha);
		}else{
			fecha = "sin fecha";
		}
		
		if(this.valpago > 0){
			BigDecimal bd = new BigDecimal(valpago);
			valor = bd.setScale(2, BigDecimal.ROUND_HALF_UP).toString();
		}else{
			valor = "sin valor";
		}
		
		this.textoExcedentes = "#" + numero + " " + fecha + " $" + valor;
		
		return textoExcedentes;
	}

	public void setTextoExcedentes(String textoExcedentes) {
		this.textoExcedentes = textoExcedentes;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codseguridad == null) ? 0 : codseguridad.hashCode());
		result = prime * result
				+ ((fcaducidad == null) ? 0 : fcaducidad.hashCode());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result
				+ ((idbcoemisor == null) ? 0 : idbcoemisor.hashCode());
		result = prime * result
				+ ((idbcoemisortar == null) ? 0 : idbcoemisortar.hashCode());
		result = prime * result + idcuenta;
		result = prime * result
				+ ((idempresa == null) ? 0 : idempresa.hashCode());
		result = prime * result + idestado;
		result = prime * result + idexcedente;
		result = prime * result + idfpago;
		result = prime * result + idpago;
		result = prime * result + idusuario;
		result = prime * result + ((ip == null) ? 0 : ip.hashCode());
		result = prime * result
				+ ((nrocuenta == null) ? 0 : nrocuenta.hashCode());
		result = prime * result
				+ ((nrodocumento == null) ? 0 : nrodocumento.hashCode());
		result = prime * result
				+ ((propietario == null) ? 0 : propietario.hashCode());
		result = prime * result + Float.floatToIntBits(valpago);
		result = prime * result + Float.floatToIntBits(valpendiente);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Excedentes other = (Excedentes) obj;
		if (codseguridad == null) {
			if (other.codseguridad != null)
				return false;
		} else if (!codseguridad.equals(other.codseguridad))
			return false;
		if (fcaducidad == null) {
			if (other.fcaducidad != null)
				return false;
		} else if (!fcaducidad.equals(other.fcaducidad))
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (idbcoemisor == null) {
			if (other.idbcoemisor != null)
				return false;
		} else if (!idbcoemisor.equals(other.idbcoemisor))
			return false;
		if (idbcoemisortar == null) {
			if (other.idbcoemisortar != null)
				return false;
		} else if (!idbcoemisortar.equals(other.idbcoemisortar))
			return false;
		if (idcuenta != other.idcuenta)
			return false;
		if (idempresa == null) {
			if (other.idempresa != null)
				return false;
		} else if (!idempresa.equals(other.idempresa))
			return false;
		if (idestado != other.idestado)
			return false;
		if (idexcedente != other.idexcedente)
			return false;
		if (idfpago != other.idfpago)
			return false;
		if (idpago != other.idpago)
			return false;
		if (idusuario != other.idusuario)
			return false;
		if (ip == null) {
			if (other.ip != null)
				return false;
		} else if (!ip.equals(other.ip))
			return false;
		if (nrocuenta == null) {
			if (other.nrocuenta != null)
				return false;
		} else if (!nrocuenta.equals(other.nrocuenta))
			return false;
		if (nrodocumento == null) {
			if (other.nrodocumento != null)
				return false;
		} else if (!nrodocumento.equals(other.nrodocumento))
			return false;
		if (propietario == null) {
			if (other.propietario != null)
				return false;
		} else if (!propietario.equals(other.propietario))
			return false;
		if (Float.floatToIntBits(valpago) != Float
				.floatToIntBits(other.valpago))
			return false;
		if (Float.floatToIntBits(valpendiente) != Float
				.floatToIntBits(other.valpendiente))
			return false;
		return true;
	}
	
	

}
