package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Impservicios generated by hbm2java
 */
@Entity
@Table(name = "impservicios", schema = "public")
public class Impservicios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7285513186160141958L;
	private int idimpservicios;
	private int idtiposervicio;
	private float valimpuesto;
	private String descripcion;
	private Date fecha;

	public Impservicios() {
	}

	public Impservicios(int idimpservicios, int idtiposervicio,
			float valimpuesto, String descripcion, Date fecha) {
		this.idimpservicios = idimpservicios;
		this.idtiposervicio = idtiposervicio;
		this.valimpuesto = valimpuesto;
		this.descripcion = descripcion;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "idimpservicios", unique = true, nullable = false)
	public int getIdimpservicios() {
		return this.idimpservicios;
	}

	public void setIdimpservicios(int idimpservicios) {
		this.idimpservicios = idimpservicios;
	}

	@Column(name = "idtiposervicio", nullable = false)
	public int getIdtiposervicio() {
		return this.idtiposervicio;
	}

	public void setIdtiposervicio(int idtiposervicio) {
		this.idtiposervicio = idtiposervicio;
	}

	@Column(name = "valimpuesto", nullable = false, precision = 8, scale = 8)
	public float getValimpuesto() {
		return this.valimpuesto;
	}

	public void setValimpuesto(float valimpuesto) {
		this.valimpuesto = valimpuesto;
	}

	@Column(name = "descripcion", nullable = false, length = 15)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
