package pojo.annotations;

// Generated 09-feb-2014 10:19:46 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", schema = "public")
public class Menu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idmenu;
	private Tipomenu tipomenu;
	private String nombre;
	private String descripcion;
	private String abreviado;
	private Integer idmenupadre;
	private Integer nivel;
	private String iconourl;
	private String paginaurl;
	private Integer orden;
	private int idestado;
	private int idempresa;


	public Menu() {
	}

	public Menu(int idmenu, int idestado, int idempresa) {
		this.idmenu = idmenu;
		this.idestado = idestado;
		this.idempresa = idempresa;
	}

	public Menu(int idmenu, Tipomenu tipomenu, String nombre,
			String descripcion, String abreviado, Integer idmenupadre,
			Integer nivel, String iconourl, String paginaurl, Integer orden,
			int idestado, int idempresa) {
		this.idmenu = idmenu;
		this.tipomenu = tipomenu;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.abreviado = abreviado;
		this.idmenupadre = idmenupadre;
		this.nivel = nivel;
		this.iconourl = iconourl;
		this.paginaurl = paginaurl;
		this.orden = orden;
		this.idestado = idestado;
		this.idempresa = idempresa;
		
	}

	@Id
	@Column(name = "idmenu", unique = true, nullable = false)
	public int getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(int idmenu) {
		this.idmenu = idmenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipomenu")
	public Tipomenu getTipomenu() {
		return this.tipomenu;
	}

	public void setTipomenu(Tipomenu tipomenu) {
		this.tipomenu = tipomenu;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idmenupadre")
	public Integer getIdmenupadre() {
		return this.idmenupadre;
	}

	public void setIdmenupadre(Integer idmenupadre) {
		this.idmenupadre = idmenupadre;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "iconourl", length = 100)
	public String getIconourl() {
		return this.iconourl;
	}

	public void setIconourl(String iconourl) {
		this.iconourl = iconourl;
	}

	@Column(name = "paginaurl", length = 200)
	public String getPaginaurl() {
		return this.paginaurl;
	}

	public void setPaginaurl(String paginaurl) {
		this.paginaurl = paginaurl;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}	

}
