package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modcronograma generated by hbm2java
 */
@Entity
@Table(name = "modcronograma", schema = "public")
public class Modcronograma implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 961758269313393388L;
	private int idmodcronograma;
	private Area area;
	private Usuario usuario;
	private Date fecha;

	public Modcronograma() {
	}

	public Modcronograma(int idmodcronograma, Area area, Usuario usuario,
			Date fecha) {
		this.idmodcronograma = idmodcronograma;
		this.area = area;
		this.usuario = usuario;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "idmodcronograma", unique = true, nullable = false)
	public int getIdmodcronograma() {
		return this.idmodcronograma;
	}

	public void setIdmodcronograma(int idmodcronograma) {
		this.idmodcronograma = idmodcronograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcronograma", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
