package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Motivos generated by hbm2java
 */
@Entity
@Table(name = "motivos", schema = "public")
public class Motivos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3592946571783858266L;
	private int idmotivo;
	private Estado estado;
	private Usuario usuario;
	private Tipomotivo tipomotivo;
	private Empresa empresa;
	private String nombre;
	private String abreviado;
	private Date fecha;
	/*private Set<?> creditoses = new HashSet<Object>(0);
	private Set<?> tipocargos = new HashSet<Object>(0);*/

	public Motivos() {
	}

	public Motivos(int idmotivo, Estado estado, Usuario usuario,
			Tipomotivo tipomotivo, Empresa empresa, String nombre, Date fecha) {
		this.idmotivo = idmotivo;
		this.estado = estado;
		this.usuario = usuario;
		this.tipomotivo = tipomotivo;
		this.empresa = empresa;
		this.nombre = nombre;
		this.fecha = fecha;
	}

	public Motivos(int idmotivo, Estado estado, Usuario usuario,
			Tipomotivo tipomotivo, Empresa empresa, String nombre,
			String abreviado, Date fecha/*, Set<?> creditoses, Set<?> tipocargos*/) {
		this.idmotivo = idmotivo;
		this.estado = estado;
		this.usuario = usuario;
		this.tipomotivo = tipomotivo;
		this.empresa = empresa;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.fecha = fecha;
		/*this.creditoses = creditoses;
		this.tipocargos = tipocargos;*/
	}

	@Id
	@Column(name = "idmotivo", unique = true, nullable = false)
	public int getIdmotivo() {
		return this.idmotivo;
	}

	public void setIdmotivo(int idmotivo) {
		this.idmotivo = idmotivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipomotivo", nullable = false)
	public Tipomotivo getTipomotivo() {
		return this.tipomotivo;
	}

	public void setTipomotivo(Tipomotivo tipomotivo) {
		this.tipomotivo = tipomotivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "motivos")
	public Set<?> getCreditoses() {
		return this.creditoses;
	}

	public void setCreditoses(Set<?> creditoses) {
		this.creditoses = creditoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motivos")
	public Set<?> getTipocargos() {
		return this.tipocargos;
	}

	public void setTipocargos(Set<?> tipocargos) {
		this.tipocargos = tipocargos;
	}*/

}
