package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nrosfactura generated by hbm2java
 */
@Entity
@Table(name = "nrosfactura", schema = "public")
public class Nrosfactura implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -994448999856255999L;
	private int idnrofactura;
	private int idempresa;
	private int idptovta;
	private int minfactura;
	private int maxfactura;
	private int idestado;
	private int autorizacion;
	private String imprenta;
	private String direccion;
	private String ruc;
	private Date fcaducidad;
	private String serieempresa;
	private String serieptovta;
	private Date fecha;
	private int idusuario;
	private String ip;
	private String resolucion;

	public Nrosfactura() {
	}

	public Nrosfactura(int idnrofactura, int idempresa, int idptovta,
			int minfactura, int maxfactura, int idestado, int autorizacion,
			String imprenta, String direccion, String ruc, Date fcaducidad,
			String serieempresa, String serieptovta, Date fecha, int idusuario,
			String ip) {
		this.idnrofactura = idnrofactura;
		this.idempresa = idempresa;
		this.idptovta = idptovta;
		this.minfactura = minfactura;
		this.maxfactura = maxfactura;
		this.idestado = idestado;
		this.autorizacion = autorizacion;
		this.imprenta = imprenta;
		this.direccion = direccion;
		this.ruc = ruc;
		this.fcaducidad = fcaducidad;
		this.serieempresa = serieempresa;
		this.serieptovta = serieptovta;
		this.fecha = fecha;
		this.idusuario = idusuario;
		this.ip = ip;
	}

	@Id
	@Column(name = "idnrofactura", unique = true, nullable = false)
	public int getIdnrofactura() {
		return this.idnrofactura;
	}

	public void setIdnrofactura(int idnrofactura) {
		this.idnrofactura = idnrofactura;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "idptovta", nullable = false)
	public int getIdptovta() {
		return this.idptovta;
	}

	public void setIdptovta(int idptovta) {
		this.idptovta = idptovta;
	}

	@Column(name = "minfactura", nullable = false)
	public int getMinfactura() {
		return this.minfactura;
	}

	public void setMinfactura(int minfactura) {
		this.minfactura = minfactura;
	}

	@Column(name = "maxfactura", nullable = false)
	public int getMaxfactura() {
		return this.maxfactura;
	}

	public void setMaxfactura(int maxfactura) {
		this.maxfactura = maxfactura;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "autorizacion", nullable = false)
	public int getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(int autorizacion) {
		this.autorizacion = autorizacion;
	}

	@Column(name = "imprenta", nullable = false, length = 30)
	public String getImprenta() {
		return this.imprenta;
	}

	public void setImprenta(String imprenta) {
		this.imprenta = imprenta;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "ruc", nullable = false, length = 20)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fcaducidad", nullable = false, length = 13)
	public Date getFcaducidad() {
		return this.fcaducidad;
	}

	public void setFcaducidad(Date fcaducidad) {
		this.fcaducidad = fcaducidad;
	}

	@Column(name = "serieempresa", nullable = false, length = 3)
	public String getSerieempresa() {
		return this.serieempresa;
	}

	public void setSerieempresa(String serieempresa) {
		this.serieempresa = serieempresa;
	}

	@Column(name = "serieptovta", nullable = false, length = 3)
	public String getSerieptovta() {
		return this.serieptovta;
	}

	public void setSerieptovta(String serieptovta) {
		this.serieptovta = serieptovta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "ip", nullable = false, length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "resolucion", length = 100)
	public String getResolucion() {
		return resolucion;
	}

	public void setResolucion(String resolucion) {
		this.resolucion = resolucion;
	}
	
	@Override
	protected Object clone() throws CloneNotSupportedException {
		Nrosfactura nrosfactura = (Nrosfactura) super.clone();
		
		return nrosfactura;
	}
	
	public Nrosfactura clonar() throws Exception {
		return (Nrosfactura) this.clone();
	}

}
