package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Operaciones generated by hbm2java
 */
@Entity
@Table(name = "operaciones", schema = "public")
public class Operaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6687571867307923568L;
	private int idoperacion;
	private Persona persona;
	private int idtipooperacion;
	private int idmotivo;
	private int idempresa;
	private String ip;
	//private Set<?> toperacioneses = new HashSet<Object>(0);

	public Operaciones() {
	}

	public Operaciones(int idoperacion, Persona persona, int idtipooperacion,
			int idmotivo, int idempresa) {
		this.idoperacion = idoperacion;
		this.persona = persona;
		this.idtipooperacion = idtipooperacion;
		this.idmotivo = idmotivo;
		this.idempresa = idempresa;
	}

	public Operaciones(int idoperacion, Persona persona, int idtipooperacion,
			int idmotivo, int idempresa, String ip/*, Set<?> toperacioneses*/) {
		this.idoperacion = idoperacion;
		this.persona = persona;
		this.idtipooperacion = idtipooperacion;
		this.idmotivo = idmotivo;
		this.idempresa = idempresa;
		this.ip = ip;
		//this.toperacioneses = toperacioneses;
	}

	@Id
	@Column(name = "idoperacion", unique = true, nullable = false)
	public int getIdoperacion() {
		return this.idoperacion;
	}

	public void setIdoperacion(int idoperacion) {
		this.idoperacion = idoperacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtecnico", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "idtipooperacion", nullable = false)
	public int getIdtipooperacion() {
		return this.idtipooperacion;
	}

	public void setIdtipooperacion(int idtipooperacion) {
		this.idtipooperacion = idtipooperacion;
	}

	@Column(name = "idmotivo", nullable = false)
	public int getIdmotivo() {
		return this.idmotivo;
	}

	public void setIdmotivo(int idmotivo) {
		this.idmotivo = idmotivo;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "operaciones")
	public Set<?> getToperacioneses() {
		return this.toperacioneses;
	}

	public void setToperacioneses(Set<?> toperacioneses) {
		this.toperacioneses = toperacioneses;
	}*/

}
