package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pagosant generated by hbm2java
 */
@Entity
@Table(name = "pagosant", schema = "public")
public class Pagosant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7640227748092196519L;
	private int idpagosant;
	private Ctacliente ctacliente;
	private Producto producto;
	private short minmeses;
	private short maxmeses;
	private short diferencia;
	private int idestado;
	private String ip;
	//private Set<?> tpagosants = new HashSet<Object>(0);

	public Pagosant() {
	}

	public Pagosant(int idpagosant, Ctacliente ctacliente, Producto producto,
			short minmeses, short maxmeses, short diferencia, int idestado) {
		this.idpagosant = idpagosant;
		this.ctacliente = ctacliente;
		this.producto = producto;
		this.minmeses = minmeses;
		this.maxmeses = maxmeses;
		this.diferencia = diferencia;
		this.idestado = idestado;
	}

	public Pagosant(int idpagosant, Ctacliente ctacliente, Producto producto,
			short minmeses, short maxmeses, short diferencia, int idestado,
			String ip/*, Set<?> tpagosants*/) {
		this.idpagosant = idpagosant;
		this.ctacliente = ctacliente;
		this.producto = producto;
		this.minmeses = minmeses;
		this.maxmeses = maxmeses;
		this.diferencia = diferencia;
		this.idestado = idestado;
		this.ip = ip;
		//this.tpagosants = tpagosants;
	}

	@Id
	@Column(name = "idpagosant", unique = true, nullable = false)
	public int getIdpagosant() {
		return this.idpagosant;
	}

	public void setIdpagosant(int idpagosant) {
		this.idpagosant = idpagosant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuenta", nullable = false)
	public Ctacliente getCtacliente() {
		return this.ctacliente;
	}

	public void setCtacliente(Ctacliente ctacliente) {
		this.ctacliente = ctacliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "minmeses", nullable = false)
	public short getMinmeses() {
		return this.minmeses;
	}

	public void setMinmeses(short minmeses) {
		this.minmeses = minmeses;
	}

	@Column(name = "maxmeses", nullable = false)
	public short getMaxmeses() {
		return this.maxmeses;
	}

	public void setMaxmeses(short maxmeses) {
		this.maxmeses = maxmeses;
	}

	@Column(name = "diferencia", nullable = false)
	public short getDiferencia() {
		return this.diferencia;
	}

	public void setDiferencia(short diferencia) {
		this.diferencia = diferencia;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "ip", length = 3)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pagosant")
	public Set<?> getTpagosants() {
		return this.tpagosants;
	}

	public void setTpagosants(Set<?> tpagosants) {
		this.tpagosants = tpagosants;
	}*/

}
