package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", schema = "public")
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7721559324587166193L;
	private int idpais;
	private String nombre;
	private String abreviado;
	private int idestado;
	private int idusuario;
	private Date fecha;
	//private Set<?> provincias = new HashSet<Object>(0);

	public Pais() {
	}

	public Pais(int idpais, String nombre, int idestado, int idusuario,
			Date fecha) {
		this.idpais = idpais;
		this.nombre = nombre;
		this.idestado = idestado;
		this.idusuario = idusuario;
		this.fecha = fecha;
	}

	public Pais(int idpais, String nombre, String abreviado, int idestado,
			int idusuario, Date fecha/*, Set<?> provincias*/) {
		this.idpais = idpais;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idestado = idestado;
		this.idusuario = idusuario;
		this.fecha = fecha;
		//this.provincias = provincias;
	}

	@Id
	@Column(name = "idpais", unique = true, nullable = false)
	public int getIdpais() {
		return this.idpais;
	}

	public void setIdpais(int idpais) {
		this.idpais = idpais;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<?> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set<?> provincias) {
		this.provincias = provincias;
	}*/

}
