package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import net.cinecable.model.base.Tidentidad;
/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
public class Persona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4006208002458986876L;
	@Id
	@SequenceGenerator(name = "Persona_GENERATOR", sequenceName = "SEQ_PERSONA", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "Persona_GENERATOR")
	@Column(name = "idpersona", unique = true, nullable = false)
	private int idpersona;
	
	@Column(name = "nombre1", nullable = false, length = 25)
	private String nombre1;
	
	@Column(name = "nombre2", nullable = false, length = 25)
	private String nombre2;
	
	@Column(name = "apellido1", nullable = false, length = 25)
	private String apellido1;
	
	@Column(name = "apellido2", nullable = false, length = 25)	
	private String apellido2;
	
	@OneToOne
	@JoinColumn(name = "idestado")
	private Estado estado;
	
	/* private int idtipocliente;
	private Integer idcodigo;  */
	
	@OneToOne
	@JoinColumn(name = "idarea")
	private Area area;
	
	@Column(name = "cargo", nullable = false)
	private String cargo;
	
	@Column(name = "idgenero", nullable = false)
	private int idgenero;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fnacimiento", length = 13)
	private Date fnacimiento;
	
	@OneToOne
	@JoinColumn(name = "idusuario")
	private Usuario usuario;
	
	@OneToOne
	@JoinColumn(name = "idtidentidad")
	private Tidentidad Tidentidad;
	
	@Column(name = "identidad")
	private String identidad;
	
	//private Set<?> operacioneses = new HashSet<Object>(0);

	public Persona() {
	}
	
		public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	/*@Id
	@Column(name = "idpersona", unique = true, nullable = false)  */
	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

//	@Column(name = "nombre1", nullable = false, length = 25)
	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	//@Column(name = "nombre2", length = 25)
	public String getNombre2() {
		return this.nombre2;
	}

	public void setNombre2(String nombre2) {
		this.nombre2 = nombre2;
	}

	//@Column(name = "apellido1", length = 25)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	//@Column(name = "apellido2", length = 25)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	/*@Column(name = "idtipocliente", nullable = false)
	public int getIdtipocliente() {
		return this.idtipocliente;
	}

	public void setIdtipocliente(int idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	@Column(name = "idcodigo")
	public Integer getIdcodigo() {
		return this.idcodigo;
	}

	public void setIdcodigo(Integer idcodigo) {
		this.idcodigo = idcodigo;
	}
*/
	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getCargo() {
		return cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public Tidentidad getTidentidad() {
		return Tidentidad;
	}

	public void setTidentidad(Tidentidad tidentidad) {
		Tidentidad = tidentidad;
	}

	public String getIdentidad() {
		return identidad;
	}

	public void setIdentidad(String identidad) {
		this.identidad = identidad;
	}
	
	@Column(name = "idgenero", nullable = false)
	public int getIdgenero() {
		return this.idgenero;
	}

	public void setIdgenero(int idgenero) {
		this.idgenero = idgenero;
	}

	
	public Date getFnacimiento() {
		return this.fnacimiento;
	}

	public void setFnacimiento(Date fnacimiento) {
		this.fnacimiento = fnacimiento;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((Tidentidad == null) ? 0 : Tidentidad.getIdtidentidad());
		result = prime * result
				+ ((apellido1 == null) ? 0 : apellido1.hashCode());
		result = prime * result
				+ ((apellido2 == null) ? 0 : apellido2.hashCode());
		result = prime * result + ((area == null) ? 0 : area.getIdarea());
		result = prime * result + ((cargo == null) ? 0 : cargo.hashCode());
		result = prime * result + ((estado == null) ? 0 : estado.getIdestado());
		result = prime * result
				+ ((fnacimiento == null) ? 0 : fnacimiento.hashCode());
		result = prime * result
				+ ((identidad == null) ? 0 : identidad.hashCode());
		result = prime * result + idgenero;
		result = prime * result + idpersona;
		result = prime * result + ((nombre1 == null) ? 0 : nombre1.hashCode());
		result = prime * result + ((nombre2 == null) ? 0 : nombre2.hashCode());
		result = prime * result + ((usuario == null) ? 0 : usuario.getIdusuario());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Persona other = (Persona) obj;
		if (Tidentidad == null) {
			if (other.Tidentidad != null)
				return false;
		} else if (Tidentidad.getIdtidentidad() != other.Tidentidad.getIdtidentidad())
			return false;
		if (apellido1 == null) {
			if (other.apellido1 != null)
				return false;
		} else if (!apellido1.equals(other.apellido1))
			return false;
		if (apellido2 == null) {
			if (other.apellido2 != null)
				return false;
		} else if (!apellido2.equals(other.apellido2))
			return false;
		if (area == null) {
			if (other.area != null)
				return false;
		} else if (area.getIdarea() != other.area.getIdarea())
			return false;
		if (cargo == null) {
			if (other.cargo != null)
				return false;
		} else if (!cargo.equals(other.cargo))
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
		} else if (estado.getIdestado() != other.estado.getIdestado())
			return false;
		if (fnacimiento == null) {
			if (other.fnacimiento != null)
				return false;
		} else if (!fnacimiento.equals(other.fnacimiento))
			return false;
		if (identidad == null) {
			if (other.identidad != null)
				return false;
		} else if (!identidad.equals(other.identidad))
			return false;
		if (idgenero != other.idgenero)
			return false;
		if (idpersona != other.idpersona)
			return false;
		if (nombre1 == null) {
			if (other.nombre1 != null)
				return false;
		} else if (!nombre1.equals(other.nombre1))
			return false;
		if (nombre2 == null) {
			if (other.nombre2 != null)
				return false;
		} else if (!nombre2.equals(other.nombre2))
			return false;
		if (usuario == null) {
			if (other.usuario != null)
				return false;
		} else if (usuario.getIdusuario() != other.usuario.getIdusuario())
			return false;
		return true;
	}
	
		
	

}
