package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
public class Persona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4006208002458986876L;
	private int idpersona;
	private String nombre1;
	private String nombre2;
	private String apellido1;
	private String apellido2;
	private int idtipocliente;
	private Integer idcodigo;
	private int idarea;
	private int idcargo;
	private int idgenero;
	private Date fnacimiento;
	//private Set<?> operacioneses = new HashSet<Object>(0);

	public Persona() {
	}

	public Persona(int idpersona, String nombre1, int idtipocliente,
			int idarea, int idcargo, int idgenero) {
		this.idpersona = idpersona;
		this.nombre1 = nombre1;
		this.idtipocliente = idtipocliente;
		this.idarea = idarea;
		this.idcargo = idcargo;
		this.idgenero = idgenero;
	}

	public Persona(int idpersona, String nombre1, String nombre2,
			String apellido1, String apellido2, int idtipocliente,
			Integer idcodigo, int idarea, int idcargo, int idgenero,
			Date fnacimiento/*, Set<?> operacioneses*/) {
		this.idpersona = idpersona;
		this.nombre1 = nombre1;
		this.nombre2 = nombre2;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.idtipocliente = idtipocliente;
		this.idcodigo = idcodigo;
		this.idarea = idarea;
		this.idcargo = idcargo;
		this.idgenero = idgenero;
		this.fnacimiento = fnacimiento;
		//this.operacioneses = operacioneses;
	}

	@Id
	@Column(name = "idpersona", unique = true, nullable = false)
	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	@Column(name = "nombre1", nullable = false, length = 25)
	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	@Column(name = "nombre2", length = 25)
	public String getNombre2() {
		return this.nombre2;
	}

	public void setNombre2(String nombre2) {
		this.nombre2 = nombre2;
	}

	@Column(name = "apellido1", length = 25)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 25)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "idtipocliente", nullable = false)
	public int getIdtipocliente() {
		return this.idtipocliente;
	}

	public void setIdtipocliente(int idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	@Column(name = "idcodigo")
	public Integer getIdcodigo() {
		return this.idcodigo;
	}

	public void setIdcodigo(Integer idcodigo) {
		this.idcodigo = idcodigo;
	}

	@Column(name = "idarea", nullable = false)
	public int getIdarea() {
		return this.idarea;
	}

	public void setIdarea(int idarea) {
		this.idarea = idarea;
	}

	@Column(name = "idcargo", nullable = false)
	public int getIdcargo() {
		return this.idcargo;
	}

	public void setIdcargo(int idcargo) {
		this.idcargo = idcargo;
	}

	@Column(name = "idgenero", nullable = false)
	public int getIdgenero() {
		return this.idgenero;
	}

	public void setIdgenero(int idgenero) {
		this.idgenero = idgenero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fnacimiento", length = 13)
	public Date getFnacimiento() {
		return this.fnacimiento;
	}

	public void setFnacimiento(Date fnacimiento) {
		this.fnacimiento = fnacimiento;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((apellido1 == null) ? 0 : apellido1.hashCode());
		result = prime * result
				+ ((apellido2 == null) ? 0 : apellido2.hashCode());
		result = prime * result
				+ ((fnacimiento == null) ? 0 : fnacimiento.hashCode());
		result = prime * result + idarea;
		result = prime * result + idcargo;
		result = prime * result
				+ ((idcodigo == null) ? 0 : idcodigo.hashCode());
		result = prime * result + idgenero;
		result = prime * result + idpersona;
		result = prime * result + idtipocliente;
		result = prime * result + ((nombre1 == null) ? 0 : nombre1.hashCode());
		result = prime * result + ((nombre2 == null) ? 0 : nombre2.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Persona other = (Persona) obj;
		if (apellido1 == null) {
			if (other.apellido1 != null)
				return false;
		} else if (!apellido1.equals(other.apellido1))
			return false;
		if (apellido2 == null) {
			if (other.apellido2 != null)
				return false;
		} else if (!apellido2.equals(other.apellido2))
			return false;
		if (fnacimiento == null) {
			if (other.fnacimiento != null)
				return false;
		} else if (!fnacimiento.equals(other.fnacimiento))
			return false;
		if (idarea != other.idarea)
			return false;
		if (idcargo != other.idcargo)
			return false;
		if (idcodigo == null) {
			if (other.idcodigo != null)
				return false;
		} else if (!idcodigo.equals(other.idcodigo))
			return false;
		if (idgenero != other.idgenero)
			return false;
		if (idpersona != other.idpersona)
			return false;
		if (idtipocliente != other.idtipocliente)
			return false;
		if (nombre1 == null) {
			if (other.nombre1 != null)
				return false;
		} else if (!nombre1.equals(other.nombre1))
			return false;
		if (nombre2 == null) {
			if (other.nombre2 != null)
				return false;
		} else if (!nombre2.equals(other.nombre2))
			return false;
		return true;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<?> getOperacioneses() {
		return this.operacioneses;
	}

	public void setOperacioneses(Set<?> operacioneses) {
		this.operacioneses = operacioneses;
	}*/
	
	

}
