package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promociones generated by hbm2java
 */
@Entity
@Table(name = "promociones", schema = "public")
public class Promociones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2636716562933448193L;
	private int idpromocion;
	private Producto producto;
	private short minimo;
	private short maximo;
	private Date fcaducidad;
	private short nivel;
	private float descuento;
	private int idempresa;
	private int idestado;
	private int idtipocliente;
	private int idusuario;
	private Date fecha;
	private String ip;

	public Promociones() {
	}

	public Promociones(int idpromocion, Producto producto, short minimo,
			short maximo, Date fcaducidad, short nivel, float descuento,
			int idempresa, int idestado, int idtipocliente, int idusuario,
			Date fecha) {
		this.idpromocion = idpromocion;
		this.producto = producto;
		this.minimo = minimo;
		this.maximo = maximo;
		this.fcaducidad = fcaducidad;
		this.nivel = nivel;
		this.descuento = descuento;
		this.idempresa = idempresa;
		this.idestado = idestado;
		this.idtipocliente = idtipocliente;
		this.idusuario = idusuario;
		this.fecha = fecha;
	}

	public Promociones(int idpromocion, Producto producto, short minimo,
			short maximo, Date fcaducidad, short nivel, float descuento,
			int idempresa, int idestado, int idtipocliente, int idusuario,
			Date fecha, String ip) {
		this.idpromocion = idpromocion;
		this.producto = producto;
		this.minimo = minimo;
		this.maximo = maximo;
		this.fcaducidad = fcaducidad;
		this.nivel = nivel;
		this.descuento = descuento;
		this.idempresa = idempresa;
		this.idestado = idestado;
		this.idtipocliente = idtipocliente;
		this.idusuario = idusuario;
		this.fecha = fecha;
		this.ip = ip;
	}

	@Id
	@Column(name = "idpromocion", unique = true, nullable = false)
	public int getIdpromocion() {
		return this.idpromocion;
	}

	public void setIdpromocion(int idpromocion) {
		this.idpromocion = idpromocion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "minimo", nullable = false)
	public short getMinimo() {
		return this.minimo;
	}

	public void setMinimo(short minimo) {
		this.minimo = minimo;
	}

	@Column(name = "maximo", nullable = false)
	public short getMaximo() {
		return this.maximo;
	}

	public void setMaximo(short maximo) {
		this.maximo = maximo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fcaducidad", nullable = false, length = 29)
	public Date getFcaducidad() {
		return this.fcaducidad;
	}

	public void setFcaducidad(Date fcaducidad) {
		this.fcaducidad = fcaducidad;
	}

	@Column(name = "nivel", nullable = false)
	public short getNivel() {
		return this.nivel;
	}

	public void setNivel(short nivel) {
		this.nivel = nivel;
	}

	@Column(name = "descuento", nullable = false, precision = 8, scale = 8)
	public float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idtipocliente", nullable = false)
	public int getIdtipocliente() {
		return this.idtipocliente;
	}

	public void setIdtipocliente(int idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
