package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", schema = "public")
public class Provincia implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6930819026807527637L;
	private int idprovincia;
	private Pais pais;
	private Usuario usuario;
	private String nombre;
	private String abreviado;
	private int idestado;
	private Date fecha;
	//private Set<?> ciudads = new HashSet<Object>(0);

	public Provincia() {
	}

	public Provincia(int idprovincia, Pais pais, Usuario usuario,
			String nombre, int idestado, Date fecha) {
		this.idprovincia = idprovincia;
		this.pais = pais;
		this.usuario = usuario;
		this.nombre = nombre;
		this.idestado = idestado;
		this.fecha = fecha;
	}

	public Provincia(int idprovincia, Pais pais, Usuario usuario,
			String nombre, String abreviado, int idestado, Date fecha/*,
			Set<?> ciudads*/) {
		this.idprovincia = idprovincia;
		this.pais = pais;
		this.usuario = usuario;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idestado = idestado;
		this.fecha = fecha;
		//this.ciudads = ciudads;
	}

	@Id
	@Column(name = "idprovincia", unique = true, nullable = false)
	public int getIdprovincia() {
		return this.idprovincia;
	}

	public void setIdprovincia(int idprovincia) {
		this.idprovincia = idprovincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<?> getCiudads() {
		return this.ciudads;
	}

	public void setCiudads(Set<?> ciudads) {
		this.ciudads = ciudads;
	}*/
	
	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	public Provincia clonar() throws Exception {
		return (Provincia)this.clone();
	}

}
