package pojo.annotations;

// Generated 12-feb-2014 15:47:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Referenciadir generated by hbm2java
 */
@Entity
@Table(name = "referenciadir", schema = "public")
public class Referenciadir implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3036772226488781364L;
	private int idreferencia;
	private String referencia;
	private int idcuenta;
	private Direccion direccion;

	public Referenciadir() {
	}

	public Referenciadir(int idreferencia, Direccion direccion, int idcuenta) {
		this.idreferencia = idreferencia;
		this.idcuenta = idcuenta;
	}

	public Referenciadir(int idreferencia, Direccion direccion,
			String referencia, int idcuenta) {
		this.idreferencia = idreferencia;
		this.referencia = referencia;
		this.idcuenta = idcuenta;
	}

	@Id
	@Column(name = "idreferencia", unique = true, nullable = false)
	public int getIdreferencia() {
		return this.idreferencia;
	}

	public void setIdreferencia(int idreferencia) {
		this.idreferencia = idreferencia;
	}



	@Column(name = "referencia", length = 2000)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "idcuenta", nullable = false)
	public int getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(int idcuenta) {
		this.idcuenta = idcuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddireccion")
	public Direccion getDireccion() {
		return direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		Referenciadir refrenciadir = (Referenciadir)super.clone(); 
		return refrenciadir;
	}
	
	public Referenciadir clonar() throws Exception {
		return (Referenciadir)this.clone();
	}
}
