package pojo.annotations;

// Generated 23/07/2015 22:32:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Saldoscierre generated by hbm2java
 */
@Entity
@Table(name = "saldoscierre", schema = "public")
public class Saldoscierre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -381168953607139129L;
	private int idsaldoscierre;
	private Usuario usuarioByIdusuariocaja;
	private Empresa empresa;
	private Usuario usuarioByIdusuario;
	private Float saldo;
	private Date fecha;
	private String iplog;

	public Saldoscierre() {
	}

	public Saldoscierre(int idsaldoscierre) {
		this.idsaldoscierre = idsaldoscierre;
	}

	public Saldoscierre(int idsaldoscierre, Usuario usuarioByIdusuariocaja,
			Empresa empresa, Usuario usuarioByIdusuario, Float saldo,
			Date fecha, String iplog) {
		this.idsaldoscierre = idsaldoscierre;
		this.usuarioByIdusuariocaja = usuarioByIdusuariocaja;
		this.empresa = empresa;
		this.usuarioByIdusuario = usuarioByIdusuario;
		this.saldo = saldo;
		this.fecha = fecha;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idsaldoscierre", unique = true, nullable = false)
	public int getIdsaldoscierre() {
		return this.idsaldoscierre;
	}

	public void setIdsaldoscierre(int idsaldoscierre) {
		this.idsaldoscierre = idsaldoscierre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuariocaja")
	public Usuario getUsuarioByIdusuariocaja() {
		return this.usuarioByIdusuariocaja;
	}

	public void setUsuarioByIdusuariocaja(Usuario usuarioByIdusuariocaja) {
		this.usuarioByIdusuariocaja = usuarioByIdusuariocaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Usuario getUsuarioByIdusuario() {
		return this.usuarioByIdusuario;
	}

	public void setUsuarioByIdusuario(Usuario usuarioByIdusuario) {
		this.usuarioByIdusuario = usuarioByIdusuario;
	}

	@Column(name = "saldo", precision = 8, scale = 8)
	public Float getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Float saldo) {
		this.saldo = saldo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
