package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", schema = "public")
public class Servicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3675896839967672190L;
	private int idservicio;
	private Tiposervicio tiposervicio;
	private String nombre;
	private String abreviado;
	private int idestado;
	private int idempresa;
	private Date fecha;
	private String idcontrolador;
	private String comunicacion;
	//private Set<?> prodservicios = new HashSet<Object>(0);
	private Costoservicio costoservicio;

	public Servicio() {
	}

	public Servicio(int idservicio, Tiposervicio tiposervicio, String nombre,
			int idestado, int idempresa, Date fecha) {
		this.idservicio = idservicio;
		this.tiposervicio = tiposervicio;
		this.nombre = nombre;
		this.idestado = idestado;
		this.idempresa = idempresa;
		this.fecha = fecha;
	}

	public Servicio(int idservicio, Tiposervicio tiposervicio, String nombre,
			String abreviado, int idestado, int idempresa, Date fecha,
			String idcontrolador, String comunicacion, /*Set<?> prodservicios,*/
			Costoservicio costoservicio) {
		this.idservicio = idservicio;
		this.tiposervicio = tiposervicio;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idestado = idestado;
		this.idempresa = idempresa;
		this.fecha = fecha;
		this.idcontrolador = idcontrolador;
		this.comunicacion = comunicacion;
		//this.prodservicios = prodservicios;
		this.costoservicio = costoservicio;
	}

	@Id
	@Column(name = "idservicio", unique = true, nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtiposervicio", nullable = false)
	public Tiposervicio getTiposervicio() {
		return this.tiposervicio;
	}

	public void setTiposervicio(Tiposervicio tiposervicio) {
		this.tiposervicio = tiposervicio;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 8)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idcontrolador", length = 20)
	public String getIdcontrolador() {
		return this.idcontrolador;
	}

	public void setIdcontrolador(String idcontrolador) {
		this.idcontrolador = idcontrolador;
	}

	@Column(name = "comunicacion", length = 20)
	public String getComunicacion() {
		return this.comunicacion;
	}

	public void setComunicacion(String comunicacion) {
		this.comunicacion = comunicacion;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<?> getProdservicios() {
		return this.prodservicios;
	}

	public void setProdservicios(Set<?> prodservicios) {
		this.prodservicios = prodservicios;
	}*/

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Costoservicio getCostoservicio() {
		return this.costoservicio;
	}

	public void setCostoservicio(Costoservicio costoservicio) {
		this.costoservicio = costoservicio;
	}

}
