package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "telefono", schema = "public")
public class Telefono implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5006152188071730933L;
	private int idtelefono;
	private Estado estado;
	private Ctacliente ctacliente;
	private String nombre;
	private int numero;
	private int idusuario;
	private Date fecha;

	public Telefono() {
	}

	public Telefono(int idtelefono, Estado estado, Ctacliente ctacliente,
			String nombre, int numero, int idusuario, Date fecha) {
		this.idtelefono = idtelefono;
		this.estado = estado;
		this.ctacliente = ctacliente;
		this.nombre = nombre;
		this.numero = numero;
		this.idusuario = idusuario;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "idtelefono", unique = true, nullable = false)
	public int getIdtelefono() {
		return this.idtelefono;
	}

	public void setIdtelefono(int idtelefono) {
		this.idtelefono = idtelefono;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcuenta", nullable = false)
	public Ctacliente getCtacliente() {
		return this.ctacliente;
	}

	public void setCtacliente(Ctacliente ctacliente) {
		this.ctacliente = ctacliente;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
