package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipomenu generated by hbm2java
 */
@Entity
@Table(name = "tipomenu", schema = "public")
public class Tipomenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -623999974588819042L;
	private int idtipomenu;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private int idestado;
	private Integer idusuario;

	public Tipomenu() {
	}

	public Tipomenu(int idtipomenu, String nombre, Date fecharegistro,
			int idestado) {
		this.idtipomenu = idtipomenu;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
		this.idestado = idestado;
	}

	public Tipomenu(int idtipomenu, String nombre, String descripcion,
			Date fecharegistro, String iplog, int idestado, Integer idusuario) {
		this.idtipomenu = idtipomenu;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.idestado = idestado;
		this.idusuario = idusuario;
	}

	@Id
	@Column(name = "idtipomenu", unique = true, nullable = false)
	public int getIdtipomenu() {
		return this.idtipomenu;
	}

	public void setIdtipomenu(int idtipomenu) {
		this.idtipomenu = idtipomenu;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idusuario")
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

}
