package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipocliente generated by hbm2java
 */
@Entity
@Table(name = "tipocliente", schema = "public")
public class Tipocliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9055582692712625627L;
	private int idtipocliente;
	private Estado estado;
	private Usuario usuario;
	private Empresa empresa;
	private String nombre;
	private String abreviado;
	private Date fecha;
	//private Set<?> clienteses = new HashSet<Object>(0);

	public Tipocliente() {
	}

	public Tipocliente(int idtipocliente, Estado estado, Usuario usuario,
			Empresa empresa, String nombre, Date fecha) {
		this.idtipocliente = idtipocliente;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre = nombre;
		this.fecha = fecha;
	}

	public Tipocliente(int idtipocliente, Estado estado, Usuario usuario,
			Empresa empresa, String nombre, String abreviado, Date fecha/*,
			Set<?> clienteses*/) {
		this.idtipocliente = idtipocliente;
		this.estado = estado;
		this.usuario = usuario;
		this.empresa = empresa;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.fecha = fecha;
		//this.clienteses = clienteses;
	}

	@Id
	@Column(name = "idtipocliente", unique = true, nullable = false)
	public int getIdtipocliente() {
		return this.idtipocliente;
	}

	public void setIdtipocliente(int idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocliente")
	public Set<?> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<?> clienteses) {
		this.clienteses = clienteses;
	}*/

}
