package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoentidad generated by hbm2java
 */
@Entity
@Table(name = "tipoentidad", schema = "public")
public class Tipoentidad implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4185595677998862415L;
	private int idtipoentidad;
	private String nombre;
	private String abreviado;
	private int idestado;
	private int idempresa;
	//private Set<?> bancoses = new HashSet<Object>(0);

	public Tipoentidad() {
	}

	public Tipoentidad(int idtipoentidad, String nombre, int idestado,
			int idempresa) {
		this.idtipoentidad = idtipoentidad;
		this.nombre = nombre;
		this.idestado = idestado;
		this.idempresa = idempresa;
	}

	public Tipoentidad(int idtipoentidad, String nombre, String abreviado,
			int idestado, int idempresa/*, Set<?> bancoses*/) {
		this.idtipoentidad = idtipoentidad;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idestado = idestado;
		this.idempresa = idempresa;
		//this.bancoses = bancoses;
	}

	@Id
	@Column(name = "idtipoentidad", unique = true, nullable = false)
	public int getIdtipoentidad() {
		return this.idtipoentidad;
	}

	public void setIdtipoentidad(int idtipoentidad) {
		this.idtipoentidad = idtipoentidad;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idempresa", nullable = false)
	public int getIdempresa() {
		return this.idempresa;
	}

	public void setIdempresa(int idempresa) {
		this.idempresa = idempresa;
	}
	
	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoentidad")
	public Set<?> getBancoses() {
		return this.bancoses;
	}

	public void setBancoses(Set<?> bancoses) {
		this.bancoses = bancoses;
	}*/

}
