package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipomotivo generated by hbm2java
 */
@Entity
@Table(name = "tipomotivo", schema = "public")
public class Tipomotivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5853223572557446342L;
	private int idtipomotivo;
	private String nombre;
	private String abreviado;
	private int idestado;
	//private Set<?> motivoses = new HashSet<Object>(0);

	public Tipomotivo() {
	}

	public Tipomotivo(int idtipomotivo, String nombre, int idestado) {
		this.idtipomotivo = idtipomotivo;
		this.nombre = nombre;
		this.idestado = idestado;
	}

	public Tipomotivo(int idtipomotivo, String nombre, String abreviado,
			int idestado/*, Set<?> motivoses*/) {
		this.idtipomotivo = idtipomotivo;
		this.nombre = nombre;
		this.abreviado = abreviado;
		this.idestado = idestado;
		//this.motivoses = motivoses;
	}

	@Id
	@Column(name = "idtipomotivo", unique = true, nullable = false)
	public int getIdtipomotivo() {
		return this.idtipomotivo;
	}

	public void setIdtipomotivo(int idtipomotivo) {
		this.idtipomotivo = idtipomotivo;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abreviado", length = 6)
	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomotivo")
	public Set<?> getMotivoses() {
		return this.motivoses;
	}

	public void setMotivoses(Set<?> motivoses) {
		this.motivoses = motivoses;
	}*/

}
