package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Toperaciones generated by hbm2java
 */
@Entity
@Table(name = "toperaciones", schema = "public")
public class Toperaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5698715501218063731L;
	private int idtoperacion;
	private Operaciones operaciones;
	private Date fecha;
	private int idusuario;
	private int idestado;
	private int idproceso;

	public Toperaciones() {
	}

	public Toperaciones(int idtoperacion, Operaciones operaciones, Date fecha,
			int idusuario, int idestado, int idproceso) {
		this.idtoperacion = idtoperacion;
		this.operaciones = operaciones;
		this.fecha = fecha;
		this.idusuario = idusuario;
		this.idestado = idestado;
		this.idproceso = idproceso;
	}

	@Id
	@Column(name = "idtoperacion", unique = true, nullable = false)
	public int getIdtoperacion() {
		return this.idtoperacion;
	}

	public void setIdtoperacion(int idtoperacion) {
		this.idtoperacion = idtoperacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperacion", nullable = false)
	public Operaciones getOperaciones() {
		return this.operaciones;
	}

	public void setOperaciones(Operaciones operaciones) {
		this.operaciones = operaciones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "idestado", nullable = false)
	public int getIdestado() {
		return this.idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	@Column(name = "idproceso", nullable = false)
	public int getIdproceso() {
		return this.idproceso;
	}

	public void setIdproceso(int idproceso) {
		this.idproceso = idproceso;
	}

}
