package pojo.annotations;

// Generated 09/02/2014 10:20:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tpagosant generated by hbm2java
 */
@Entity
@Table(name = "tpagosant", schema = "public")
public class Tpagosant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5289442634728736346L;
	private int idtpagosant;
	private Pagosant pagosant;
	private int idusuario;
	private int meses;
	private Date fecha;

	public Tpagosant() {
	}

	public Tpagosant(int idtpagosant, Pagosant pagosant, int idusuario,
			int meses, Date fecha) {
		this.idtpagosant = idtpagosant;
		this.pagosant = pagosant;
		this.idusuario = idusuario;
		this.meses = meses;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "idtpagosant", unique = true, nullable = false)
	public int getIdtpagosant() {
		return this.idtpagosant;
	}

	public void setIdtpagosant(int idtpagosant) {
		this.idtpagosant = idtpagosant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpagosant", nullable = false)
	public Pagosant getPagosant() {
		return this.pagosant;
	}

	public void setPagosant(Pagosant pagosant) {
		this.pagosant = pagosant;
	}

	@Column(name = "idusuario", nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "meses", nullable = false)
	public int getMeses() {
		return this.meses;
	}

	public void setMeses(int meses) {
		this.meses = meses;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
